# Form implementation generated from reading ui file 'src/gui/analytics.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Analytics(object):
    def setupUi(self, Analytics):
        Analytics.setObjectName("Analytics")
        Analytics.resize(1280, 860)
        Analytics.setStyleSheet("""
/* ===== Giao diện Phân tích Bán hàng (Chuẩn Design) ===== */
QWidget#Analytics {
    background-color: #f8fafc;
}

QLabel {
    background-color: transparent;
    border: none;
    color: #0f172a;
}

/* Khung toggle thời gian (Hôm nay / Tuần này / Tháng này) */
QFrame#framePeriodToggle {
    background-color: #ffffff;
    border: 1px solid #e2e8f0;
    border-radius: 8px;
    padding: 2px;
}

QPushButton.periodToggleBtn {
    background-color: transparent;
    color: #475569;
    border: none;
    border-radius: 6px;
    padding: 6px 14px;
    font-size: 13px;
    font-weight: bold;
}
QPushButton.periodToggleBtn:hover {
    background-color: #f1f5f9;
    color: #0f172a;
}
QPushButton.periodToggleBtn:checked {
    background-color: #002d72;
    color: #ffffff;
}

/* Thẻ KPI */
QFrame.kpiCard {
    background-color: #ffffff;
    border-radius: 12px;
    border: 1px solid #e2e8f0;
}

/* Khung nội dung trắng */
QFrame.contentCard {
    background-color: #ffffff;
    border-radius: 12px;
    border: 1px solid #e2e8f0;
}

/* Bảng Top sản phẩm bán chạy */
QTableWidget#tblTopProducts {
    border: none;
    gridline-color: transparent;
    background-color: #ffffff;
}
QTableWidget#tblTopProducts::item {
    padding: 12px 8px;
    border-bottom: 1px solid #f1f5f9;
    color: #0f172a;
}
QHeaderView::section {
    background-color: #f8fafc;
    padding: 10px 8px;
    font-weight: 700;
    font-size: 11px;
    border: none;
    border-bottom: 1px solid #e2e8f0;
    color: #64748b;
}
""")
        self.rootLayout = QtWidgets.QVBoxLayout(Analytics)
        self.rootLayout.setContentsMargins(20, 20, 20, 20)
        self.rootLayout.setSpacing(16)
        self.rootLayout.setObjectName("rootLayout")

        # --- Top Header ---
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")

        self.titleLayout = QtWidgets.QVBoxLayout()
        self.titleLayout.setSpacing(3)
        self.titleLayout.setObjectName("titleLayout")

        self.lblTitle = QtWidgets.QLabel(parent=Analytics)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.titleLayout.addWidget(self.lblTitle)

        self.lblSubtitle = QtWidgets.QLabel(parent=Analytics)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.lblSubtitle.setFont(font)
        self.lblSubtitle.setStyleSheet("color: #64748b;")
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.titleLayout.addWidget(self.lblSubtitle)

        self.headerLayout.addLayout(self.titleLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)

        # Toggle Button Group (Hôm nay / Tuần này / Tháng này)
        self.framePeriodToggle = QtWidgets.QFrame(parent=Analytics)
        self.framePeriodToggle.setObjectName("framePeriodToggle")
        self.toggleLayout = QtWidgets.QHBoxLayout(self.framePeriodToggle)
        self.toggleLayout.setContentsMargins(3, 3, 3, 3)
        self.toggleLayout.setSpacing(2)

        self.btnPeriodToday = QtWidgets.QPushButton(parent=self.framePeriodToggle)
        self.btnPeriodToday.setCheckable(True)
        self.btnPeriodToday.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPeriodToday.setProperty("class", "periodToggleBtn")
        self.btnPeriodToday.setObjectName("btnPeriodToday")
        self.toggleLayout.addWidget(self.btnPeriodToday)

        self.btnPeriodWeek = QtWidgets.QPushButton(parent=self.framePeriodToggle)
        self.btnPeriodWeek.setCheckable(True)
        self.btnPeriodWeek.setChecked(True)
        self.btnPeriodWeek.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPeriodWeek.setProperty("class", "periodToggleBtn")
        self.btnPeriodWeek.setObjectName("btnPeriodWeek")
        self.toggleLayout.addWidget(self.btnPeriodWeek)

        self.btnPeriodMonth = QtWidgets.QPushButton(parent=self.framePeriodToggle)
        self.btnPeriodMonth.setCheckable(True)
        self.btnPeriodMonth.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPeriodMonth.setProperty("class", "periodToggleBtn")
        self.btnPeriodMonth.setObjectName("btnPeriodMonth")
        self.toggleLayout.addWidget(self.btnPeriodMonth)

        self.headerLayout.addWidget(self.framePeriodToggle)
        self.rootLayout.addLayout(self.headerLayout)

        # --- 4 Thẻ KPI ---
        self.cardsLayout = QtWidgets.QHBoxLayout()
        self.cardsLayout.setSpacing(16)
        self.cardsLayout.setObjectName("cardsLayout")

        # Card 1: TỔNG DOANH THU
        self.cardRevenue = QtWidgets.QFrame(parent=Analytics)
        self.cardRevenue.setProperty("class", "kpiCard")
        self.cardRevenue.setMinimumSize(QtCore.QSize(0, 120))
        self.cardRevenueLayout = QtWidgets.QVBoxLayout(self.cardRevenue)
        self.cardRevenueLayout.setContentsMargins(18, 16, 18, 16)
        self.cardRevenueLayout.setSpacing(6)

        self.row1Rev = QtWidgets.QHBoxLayout()
        self.lblRevenueTitle = QtWidgets.QLabel(parent=self.cardRevenue)
        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(9)
        self.lblRevenueTitle.setFont(font)
        self.lblRevenueTitle.setStyleSheet("color: #64748b;")
        self.row1Rev.addWidget(self.lblRevenueTitle)
        self.row1Rev.addStretch()
        self.badgeRevenue = QtWidgets.QLabel(parent=self.cardRevenue)
        self.badgeRevenue.setFixedSize(36, 36)
        self.badgeRevenue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.badgeRevenue.setStyleSheet("background-color: #e0edff; border-radius: 8px;")
        self.row1Rev.addWidget(self.badgeRevenue)
        self.cardRevenueLayout.addLayout(self.row1Rev)

        self.lblRevenueVal = QtWidgets.QLabel(parent=self.cardRevenue)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.lblRevenueVal.setFont(font)
        self.cardRevenueLayout.addWidget(self.lblRevenueVal)

        self.lblRevenueTrend = QtWidgets.QLabel(parent=self.cardRevenue)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.lblRevenueTrend.setFont(font)
        self.lblRevenueTrend.setStyleSheet("background-color: #ecfdf5; color: #059669; border-radius: 4px; padding: 2px 6px;")
        self.cardRevenueLayout.addWidget(self.lblRevenueTrend, alignment=QtCore.Qt.AlignmentFlag.AlignLeft)
        self.cardsLayout.addWidget(self.cardRevenue)

        # Card 2: ĐƠN HÀNG
        self.cardOrders = QtWidgets.QFrame(parent=Analytics)
        self.cardOrders.setProperty("class", "kpiCard")
        self.cardOrders.setMinimumSize(QtCore.QSize(0, 120))
        self.cardOrdersLayout = QtWidgets.QVBoxLayout(self.cardOrders)
        self.cardOrdersLayout.setContentsMargins(18, 16, 18, 16)
        self.cardOrdersLayout.setSpacing(6)

        self.row1Orders = QtWidgets.QHBoxLayout()
        self.lblOrdersTitle = QtWidgets.QLabel(parent=self.cardOrders)
        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(9)
        self.lblOrdersTitle.setFont(font)
        self.lblOrdersTitle.setStyleSheet("color: #64748b;")
        self.row1Orders.addWidget(self.lblOrdersTitle)
        self.row1Orders.addStretch()
        self.badgeOrders = QtWidgets.QLabel(parent=self.cardOrders)
        self.badgeOrders.setFixedSize(36, 36)
        self.badgeOrders.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.badgeOrders.setStyleSheet("background-color: #e0edff; border-radius: 8px;")
        self.row1Orders.addWidget(self.badgeOrders)
        self.cardOrdersLayout.addLayout(self.row1Orders)

        self.lblOrdersVal = QtWidgets.QLabel(parent=self.cardOrders)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.lblOrdersVal.setFont(font)
        self.cardOrdersLayout.addWidget(self.lblOrdersVal)

        self.lblOrdersTrend = QtWidgets.QLabel(parent=self.cardOrders)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.lblOrdersTrend.setFont(font)
        self.lblOrdersTrend.setStyleSheet("background-color: #ecfdf5; color: #059669; border-radius: 4px; padding: 2px 6px;")
        self.cardOrdersLayout.addWidget(self.lblOrdersTrend, alignment=QtCore.Qt.AlignmentFlag.AlignLeft)
        self.cardsLayout.addWidget(self.cardOrders)

        # Card 3: GTTB ĐƠN (AOV)
        self.cardAov = QtWidgets.QFrame(parent=Analytics)
        self.cardAov.setProperty("class", "kpiCard")
        self.cardAov.setMinimumSize(QtCore.QSize(0, 120))
        self.cardAovLayout = QtWidgets.QVBoxLayout(self.cardAov)
        self.cardAovLayout.setContentsMargins(18, 16, 18, 16)
        self.cardAovLayout.setSpacing(6)

        self.row1Aov = QtWidgets.QHBoxLayout()
        self.lblAovTitle = QtWidgets.QLabel(parent=self.cardAov)
        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(9)
        self.lblAovTitle.setFont(font)
        self.lblAovTitle.setStyleSheet("color: #64748b;")
        self.row1Aov.addWidget(self.lblAovTitle)
        self.row1Aov.addStretch()
        self.badgeAov = QtWidgets.QLabel(parent=self.cardAov)
        self.badgeAov.setFixedSize(36, 36)
        self.badgeAov.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.badgeAov.setStyleSheet("background-color: #e0edff; border-radius: 8px;")
        self.row1Aov.addWidget(self.badgeAov)
        self.cardAovLayout.addLayout(self.row1Aov)

        self.lblAovVal = QtWidgets.QLabel(parent=self.cardAov)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.lblAovVal.setFont(font)
        self.cardAovLayout.addWidget(self.lblAovVal)

        self.lblAovTrend = QtWidgets.QLabel(parent=self.cardAov)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.lblAovTrend.setFont(font)
        self.lblAovTrend.setStyleSheet("background-color: #fef2f2; color: #dc2626; border-radius: 4px; padding: 2px 6px;")
        self.cardAovLayout.addWidget(self.lblAovTrend, alignment=QtCore.Qt.AlignmentFlag.AlignLeft)
        self.cardsLayout.addWidget(self.cardAov)

        # Card 4: KHÁCH QUAY LẠI
        self.cardReturn = QtWidgets.QFrame(parent=Analytics)
        self.cardReturn.setProperty("class", "kpiCard")
        self.cardReturn.setMinimumSize(QtCore.QSize(0, 120))
        self.cardReturnLayout = QtWidgets.QVBoxLayout(self.cardReturn)
        self.cardReturnLayout.setContentsMargins(18, 16, 18, 16)
        self.cardReturnLayout.setSpacing(6)

        self.row1Return = QtWidgets.QHBoxLayout()
        self.lblReturnTitle = QtWidgets.QLabel(parent=self.cardReturn)
        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(9)
        self.lblReturnTitle.setFont(font)
        self.lblReturnTitle.setStyleSheet("color: #64748b;")
        self.row1Return.addWidget(self.lblReturnTitle)
        self.row1Return.addStretch()
        self.badgeReturn = QtWidgets.QLabel(parent=self.cardReturn)
        self.badgeReturn.setFixedSize(36, 36)
        self.badgeReturn.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.badgeReturn.setStyleSheet("background-color: #e0edff; border-radius: 8px;")
        self.row1Return.addWidget(self.badgeReturn)
        self.cardReturnLayout.addLayout(self.row1Return)

        self.lblReturnVal = QtWidgets.QLabel(parent=self.cardReturn)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.lblReturnVal.setFont(font)
        self.cardReturnLayout.addWidget(self.lblReturnVal)

        self.lblReturnTrend = QtWidgets.QLabel(parent=self.cardReturn)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.lblReturnTrend.setFont(font)
        self.lblReturnTrend.setStyleSheet("background-color: #ecfdf5; color: #059669; border-radius: 4px; padding: 2px 6px;")
        self.cardReturnLayout.addWidget(self.lblReturnTrend, alignment=QtCore.Qt.AlignmentFlag.AlignLeft)
        self.cardsLayout.addWidget(self.cardReturn)

        self.rootLayout.addLayout(self.cardsLayout)

        # --- Middle Row: Biểu đồ thời gian (Trái) + Cơ cấu danh mục (Phải) ---
        self.middleLayout = QtWidgets.QHBoxLayout()
        self.middleLayout.setSpacing(16)
        self.middleLayout.setObjectName("middleLayout")

        # Khung Biểu đồ Doanh thu theo thời gian
        self.cardTimeChart = QtWidgets.QFrame(parent=Analytics)
        self.cardTimeChart.setProperty("class", "contentCard")
        self.timeChartLayout = QtWidgets.QVBoxLayout(self.cardTimeChart)
        self.timeChartLayout.setContentsMargins(18, 16, 18, 16)
        self.timeChartLayout.setSpacing(10)

        self.timeChartHeader = QtWidgets.QHBoxLayout()
        self.lblTimeChartTitle = QtWidgets.QLabel(parent=self.cardTimeChart)
        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(10)
        self.lblTimeChartTitle.setFont(font)
        self.timeChartHeader.addWidget(self.lblTimeChartTitle)
        self.timeChartHeader.addStretch()

        self.btnDetailLink = QtWidgets.QPushButton(parent=self.cardTimeChart)
        self.btnDetailLink.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnDetailLink.setStyleSheet("background: transparent; border: none; color: #002d72; font-size: 12px; font-weight: bold;")
        self.timeChartHeader.addWidget(self.btnDetailLink)
        self.timeChartLayout.addLayout(self.timeChartHeader)

        self.containerTimeChart = QtWidgets.QWidget(parent=self.cardTimeChart)
        self.containerTimeChart.setMinimumHeight(210)
        self.timeChartLayout.addWidget(self.containerTimeChart)

        self.middleLayout.addWidget(self.cardTimeChart, stretch=6)

        # Khung Cơ cấu danh mục bán chạy
        self.cardCategory = QtWidgets.QFrame(parent=Analytics)
        self.cardCategory.setProperty("class", "contentCard")
        self.categoryLayout = QtWidgets.QVBoxLayout(self.cardCategory)
        self.categoryLayout.setContentsMargins(18, 16, 18, 16)
        self.categoryLayout.setSpacing(10)

        self.lblCategoryTitle = QtWidgets.QLabel(parent=self.cardCategory)
        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(10)
        self.lblCategoryTitle.setFont(font)
        self.categoryLayout.addWidget(self.lblCategoryTitle)

        self.containerCategoryList = QtWidgets.QVBoxLayout()
        self.containerCategoryList.setSpacing(12)
        self.categoryLayout.addLayout(self.containerCategoryList)
        self.categoryLayout.addStretch()

        self.middleLayout.addWidget(self.cardCategory, stretch=4)
        self.rootLayout.addLayout(self.middleLayout, stretch=4)

        # --- Bottom Row: Top sản phẩm bán chạy ---
        self.cardTopProducts = QtWidgets.QFrame(parent=Analytics)
        self.cardTopProducts.setProperty("class", "contentCard")
        self.topProductsLayout = QtWidgets.QVBoxLayout(self.cardTopProducts)
        self.topProductsLayout.setContentsMargins(18, 16, 18, 16)
        self.topProductsLayout.setSpacing(10)

        self.lblTopProductsTitle = QtWidgets.QLabel(parent=self.cardTopProducts)
        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(10)
        self.lblTopProductsTitle.setFont(font)
        self.topProductsLayout.addWidget(self.lblTopProductsTitle)

        self.tblTopProducts = QtWidgets.QTableWidget(parent=self.cardTopProducts)
        self.tblTopProducts.setObjectName("tblTopProducts")
        self.tblTopProducts.setColumnCount(3)
        self.tblTopProducts.setRowCount(0)
        self.topProductsLayout.addWidget(self.tblTopProducts)

        self.rootLayout.addWidget(self.cardTopProducts, stretch=3)

        self.retranslateUi(Analytics)
        QtCore.QMetaObject.connectSlotsByName(Analytics)

    def retranslateUi(self, Analytics):
        _translate = QtCore.QCoreApplication.translate
        Analytics.setWindowTitle(_translate("Analytics", "Phân tích bán hàng"))
        self.lblTitle.setText(_translate("Analytics", "Phân tích Bán hàng"))
        self.lblSubtitle.setText(_translate("Analytics", "Tổng quan hiệu suất kinh doanh và xu hướng."))
        self.btnPeriodToday.setText(_translate("Analytics", "Hôm nay"))
        self.btnPeriodWeek.setText(_translate("Analytics", "Tuần này"))
        self.btnPeriodMonth.setText(_translate("Analytics", "Tháng này"))
        self.lblRevenueTitle.setText(_translate("Analytics", "TỔNG DOANH THU"))
        self.lblRevenueVal.setText(_translate("Analytics", "₫452M"))
        self.lblRevenueTrend.setText(_translate("Analytics", "↗ +12.5% so với tuần trước"))
        self.lblOrdersTitle.setText(_translate("Analytics", "ĐƠN HÀNG"))
        self.lblOrdersVal.setText(_translate("Analytics", "1,245"))
        self.lblOrdersTrend.setText(_translate("Analytics", "↗ +8.2%"))
        self.lblAovTitle.setText(_translate("Analytics", "GTTB ĐƠN (AOV)"))
        self.lblAovVal.setText(_translate("Analytics", "₫363K"))
        self.lblAovTrend.setText(_translate("Analytics", "↘ -2.1%"))
        self.lblReturnTitle.setText(_translate("Analytics", "KHÁCH QUAY LẠI"))
        self.lblReturnVal.setText(_translate("Analytics", "42.8%"))
        self.lblReturnTrend.setText(_translate("Analytics", "↗ +5.4%"))
        self.lblTimeChartTitle.setText(_translate("Analytics", "Doanh thu theo thời gian"))
        self.btnDetailLink.setText(_translate("Analytics", "Xem chi tiết"))
        self.lblCategoryTitle.setText(_translate("Analytics", "Cơ cấu danh mục bán chạy"))
        self.lblTopProductsTitle.setText(_translate("Analytics", "Top sản phẩm bán chạy"))
