# Form implementation generated from reading ui file 'src/gui/customer_management.ui'
#
# Created by: PySide6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_CustomerManagement(object):
    def setupUi(self, CustomerManagement):
        CustomerManagement.setObjectName("CustomerManagement")
        CustomerManagement.resize(1280, 860)
        CustomerManagement.setStyleSheet("""
/* ===== Giao diện Quản lý Khách hàng (Chuẩn Design) ===== */
QWidget#CustomerManagement {
    background-color: #f8fafc;
}

QLabel {
    background-color: transparent;
    border: none;
    color: #0f172a;
}

/* Nút Header */
QPushButton#btnPurchaseHistory {
    background-color: #ffffff;
    color: #1e293b;
    border: 1px solid #cbd5e1;
    border-radius: 8px;
    padding: 0px 16px;
    font-size: 13px;
    font-weight: bold;
}
QPushButton#btnPurchaseHistory:hover {
    background-color: #f1f5f9;
}
QPushButton#btnPurchaseHistory:pressed {
    background-color: #e2e8f0;
}

QPushButton#btnAddCustomer {
    background-color: #002d72;
    color: #ffffff;
    border: none;
    border-radius: 8px;
    padding: 0px 18px;
    font-size: 13px;
    font-weight: bold;
}
QPushButton#btnAddCustomer:hover {
    background-color: #0d2b6b;
}
QPushButton#btnAddCustomer:pressed {
    background-color: #091e4a;
}

/* Thẻ tổng quan Overview Cards */
QFrame.cardOverview {
    background-color: #ffffff;
    border-radius: 12px;
    border: 1px solid #e2e8f0;
}

/* Khung Bảng & Bộ lọc */
QFrame#cardTableContainer {
    background-color: #ffffff;
    border-radius: 12px;
    border: 1px solid #e2e8f0;
}

QLineEdit#txtSearch {
    background-color: #ffffff;
    border: 1px solid #e2e8f0;
    border-radius: 8px;
    padding: 4px 14px;
    font-size: 13px;
    color: #0f172a;
}
QLineEdit#txtSearch:focus {
    border: 1px solid #002d72;
}

QPushButton#btnFilter {
    background-color: #ffffff;
    border: 1px solid #e2e8f0;
    border-radius: 8px;
}
QPushButton#btnFilter:hover {
    background-color: #f1f5f9;
}

QPushButton#btnEditCustomer {
    background-color: #ffffff;
    color: #1d4ed8;
    border: 1px solid #bfdbfe;
    border-radius: 8px;
    padding: 0px 12px;
    font-size: 13px;
    font-weight: bold;
}
QPushButton#btnEditCustomer:hover {
    background-color: #eff6ff;
}

QPushButton#btnDeleteCustomer {
    background-color: #ffffff;
    color: #dc2626;
    border: 1px solid #fecaca;
    border-radius: 8px;
    padding: 0px 12px;
    font-size: 13px;
    font-weight: bold;
}
QPushButton#btnDeleteCustomer:hover {
    background-color: #fef2f2;
}

QPushButton.pageBtn {
    background-color: #ffffff;
    border: 1px solid #e2e8f0;
    border-radius: 6px;
    color: #475569;
    font-weight: bold;
}
QPushButton.pageBtn:hover {
    background-color: #f1f5f9;
}
QPushButton.pageBtn:disabled {
    background-color: #f8fafc;
    color: #cbd5e1;
}

/* Bảng */
QTableWidget#tblCustomers {
    border: none;
    gridline-color: transparent;
    background-color: #ffffff;
    selection-background-color: #e0edff;
    selection-color: #0f172a;
}
QTableWidget#tblCustomers::item {
    padding: 4px 8px;
    border-bottom: 1px solid #f1f5f9;
    color: #0f172a;
}
QHeaderView::section {
    background-color: #ffffff;
    padding: 10px 8px;
    font-weight: 600;
    font-size: 12px;
    border: none;
    border-bottom: 1px solid #e2e8f0;
    color: #475569;
}

/* Nút tải thêm dữ liệu */
QPushButton#btnLoadMore {
    background-color: transparent;
    color: #002d72;
    border: none;
    border-radius: 8px;
    font-size: 13px;
    font-weight: bold;
    padding: 8px;
}
QPushButton#btnLoadMore:hover {
    background-color: #f1f5f9;
}
""")
        self.rootLayout = QtWidgets.QVBoxLayout(CustomerManagement)
        self.rootLayout.setContentsMargins(20, 20, 20, 20)
        self.rootLayout.setSpacing(16)
        self.rootLayout.setObjectName("rootLayout")

        # --- Top Header ---
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")

        self.titleLayout = QtWidgets.QVBoxLayout()
        self.titleLayout.setSpacing(3)
        self.titleLayout.setObjectName("titleLayout")

        self.lblTitle = QtWidgets.QLabel(parent=CustomerManagement)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.titleLayout.addWidget(self.lblTitle)

        self.lblSubtitle = QtWidgets.QLabel(parent=CustomerManagement)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.lblSubtitle.setFont(font)
        self.lblSubtitle.setStyleSheet("color: #64748b;")
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.titleLayout.addWidget(self.lblSubtitle)

        self.headerLayout.addLayout(self.titleLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)

        self.btnPurchaseHistory = QtWidgets.QPushButton(parent=CustomerManagement)
        self.btnPurchaseHistory.setMinimumSize(QtCore.QSize(190, 40))
        self.btnPurchaseHistory.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPurchaseHistory.setObjectName("btnPurchaseHistory")
        self.headerLayout.addWidget(self.btnPurchaseHistory)

        self.btnAddCustomer = QtWidgets.QPushButton(parent=CustomerManagement)
        self.btnAddCustomer.setMinimumSize(QtCore.QSize(180, 40))
        self.btnAddCustomer.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnAddCustomer.setObjectName("btnAddCustomer")
        self.headerLayout.addWidget(self.btnAddCustomer)

        self.rootLayout.addLayout(self.headerLayout)

        # --- 3 Thẻ thống kê (Cards) ---
        self.cardsLayout = QtWidgets.QHBoxLayout()
        self.cardsLayout.setSpacing(16)
        self.cardsLayout.setObjectName("cardsLayout")

        # Card 1: Tổng Thành Viên
        self.cardTotal = QtWidgets.QFrame(parent=CustomerManagement)
        self.cardTotal.setProperty("class", "cardOverview")
        self.cardTotal.setMinimumSize(QtCore.QSize(0, 115))
        self.cardTotalLayout = QtWidgets.QVBoxLayout(self.cardTotal)
        self.cardTotalLayout.setContentsMargins(18, 16, 18, 16)
        self.cardTotalLayout.setSpacing(6)

        self.row1Total = QtWidgets.QHBoxLayout()
        self.lblTotalTitle = QtWidgets.QLabel(parent=self.cardTotal)
        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(10)
        self.lblTotalTitle.setFont(font)
        self.lblTotalTitle.setStyleSheet("color: #475569;")
        self.row1Total.addWidget(self.lblTotalTitle)
        self.row1Total.addStretch()
        self.badgeTotal = QtWidgets.QLabel(parent=self.cardTotal)
        self.badgeTotal.setFixedSize(36, 36)
        self.badgeTotal.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.badgeTotal.setStyleSheet("background-color: #e0edff; border-radius: 8px;")
        self.row1Total.addWidget(self.badgeTotal)
        self.cardTotalLayout.addLayout(self.row1Total)

        self.lblTotalVal = QtWidgets.QLabel(parent=self.cardTotal)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.lblTotalVal.setFont(font)
        self.cardTotalLayout.addWidget(self.lblTotalVal)

        self.lblTotalTrend = QtWidgets.QLabel(parent=self.cardTotal)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.lblTotalTrend.setFont(font)
        self.lblTotalTrend.setStyleSheet("color: #2563eb;")
        self.cardTotalLayout.addWidget(self.lblTotalTrend)
        self.cardsLayout.addWidget(self.cardTotal)

        # Card 2: Hoạt động (Tháng này)
        self.cardActive = QtWidgets.QFrame(parent=CustomerManagement)
        self.cardActive.setProperty("class", "cardOverview")
        self.cardActive.setMinimumSize(QtCore.QSize(0, 115))
        self.cardActiveLayout = QtWidgets.QVBoxLayout(self.cardActive)
        self.cardActiveLayout.setContentsMargins(18, 16, 18, 16)
        self.cardActiveLayout.setSpacing(6)

        self.row1Active = QtWidgets.QHBoxLayout()
        self.lblActiveTitle = QtWidgets.QLabel(parent=self.cardActive)
        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(10)
        self.lblActiveTitle.setFont(font)
        self.lblActiveTitle.setStyleSheet("color: #475569;")
        self.row1Active.addWidget(self.lblActiveTitle)
        self.row1Active.addStretch()
        self.badgeActive = QtWidgets.QLabel(parent=self.cardActive)
        self.badgeActive.setFixedSize(36, 36)
        self.badgeActive.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.badgeActive.setStyleSheet("background-color: #e6f9f0; border-radius: 8px;")
        self.row1Active.addWidget(self.badgeActive)
        self.cardActiveLayout.addLayout(self.row1Active)

        self.lblActiveVal = QtWidgets.QLabel(parent=self.cardActive)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.lblActiveVal.setFont(font)
        self.cardActiveLayout.addWidget(self.lblActiveVal)

        self.lblActiveTrend = QtWidgets.QLabel(parent=self.cardActive)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.lblActiveTrend.setFont(font)
        self.lblActiveTrend.setStyleSheet("color: #64748b;")
        self.cardActiveLayout.addWidget(self.lblActiveTrend)
        self.cardsLayout.addWidget(self.cardActive)

        # Card 3: Điểm đã phát hành
        self.cardPoints = QtWidgets.QFrame(parent=CustomerManagement)
        self.cardPoints.setProperty("class", "cardOverview")
        self.cardPoints.setMinimumSize(QtCore.QSize(0, 115))
        self.cardPointsLayout = QtWidgets.QVBoxLayout(self.cardPoints)
        self.cardPointsLayout.setContentsMargins(18, 16, 18, 16)
        self.cardPointsLayout.setSpacing(6)

        self.row1Points = QtWidgets.QHBoxLayout()
        self.lblPointsTitle = QtWidgets.QLabel(parent=self.cardPoints)
        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(10)
        self.lblPointsTitle.setFont(font)
        self.lblPointsTitle.setStyleSheet("color: #475569;")
        self.row1Points.addWidget(self.lblPointsTitle)
        self.row1Points.addStretch()
        self.badgePoints = QtWidgets.QLabel(parent=self.cardPoints)
        self.badgePoints.setFixedSize(36, 36)
        self.badgePoints.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.badgePoints.setStyleSheet("background-color: #fff4e5; border-radius: 8px;")
        self.row1Points.addWidget(self.badgePoints)
        self.cardPointsLayout.addLayout(self.row1Points)

        self.lblPointsVal = QtWidgets.QLabel(parent=self.cardPoints)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.lblPointsVal.setFont(font)
        self.cardPointsLayout.addWidget(self.lblPointsVal)

        self.lblPointsTrend = QtWidgets.QLabel(parent=self.cardPoints)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.lblPointsTrend.setFont(font)
        self.lblPointsTrend.setStyleSheet("color: #2563eb;")
        self.cardPointsLayout.addWidget(self.lblPointsTrend)
        self.cardsLayout.addWidget(self.cardPoints)

        self.rootLayout.addLayout(self.cardsLayout)

        # --- Table Container Card ---
        self.cardTableContainer = QtWidgets.QFrame(parent=CustomerManagement)
        self.cardTableContainer.setObjectName("cardTableContainer")
        self.tableContainerLayout = QtWidgets.QVBoxLayout(self.cardTableContainer)
        self.tableContainerLayout.setContentsMargins(16, 16, 16, 16)
        self.tableContainerLayout.setSpacing(12)

        # Toolbar Row (Search + Filter + Edit + Delete + Pagination)
        self.toolbarLayout = QtWidgets.QHBoxLayout()
        self.toolbarLayout.setSpacing(10)
        self.toolbarLayout.setObjectName("toolbarLayout")

        self.txtSearch = QtWidgets.QLineEdit(parent=self.cardTableContainer)
        self.txtSearch.setMinimumSize(QtCore.QSize(240, 38))
        self.txtSearch.setMaximumSize(QtCore.QSize(300, 38))
        self.txtSearch.setObjectName("txtSearch")
        self.toolbarLayout.addWidget(self.txtSearch)

        self.btnFilter = QtWidgets.QPushButton(parent=self.cardTableContainer)
        self.btnFilter.setFixedSize(38, 38)
        self.btnFilter.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnFilter.setObjectName("btnFilter")
        self.toolbarLayout.addWidget(self.btnFilter)

        self.btnEditCustomer = QtWidgets.QPushButton(parent=self.cardTableContainer)
        self.btnEditCustomer.setMinimumSize(QtCore.QSize(85, 38))
        self.btnEditCustomer.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnEditCustomer.setObjectName("btnEditCustomer")
        self.toolbarLayout.addWidget(self.btnEditCustomer)

        self.btnDeleteCustomer = QtWidgets.QPushButton(parent=self.cardTableContainer)
        self.btnDeleteCustomer.setMinimumSize(QtCore.QSize(85, 38))
        self.btnDeleteCustomer.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnDeleteCustomer.setObjectName("btnDeleteCustomer")
        self.toolbarLayout.addWidget(self.btnDeleteCustomer)

        self.toolbarLayout.addStretch()

        self.lblPaginationInfo = QtWidgets.QLabel(parent=self.cardTableContainer)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblPaginationInfo.setFont(font)
        self.lblPaginationInfo.setStyleSheet("color: #64748b;")
        self.lblPaginationInfo.setObjectName("lblPaginationInfo")
        self.toolbarLayout.addWidget(self.lblPaginationInfo)

        self.btnPrevPage = QtWidgets.QPushButton(parent=self.cardTableContainer)
        self.btnPrevPage.setFixedSize(30, 30)
        self.btnPrevPage.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPrevPage.setProperty("class", "pageBtn")
        self.btnPrevPage.setObjectName("btnPrevPage")
        self.btnPrevPage.setText("<")
        self.toolbarLayout.addWidget(self.btnPrevPage)

        self.btnNextPage = QtWidgets.QPushButton(parent=self.cardTableContainer)
        self.btnNextPage.setFixedSize(30, 30)
        self.btnNextPage.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnNextPage.setProperty("class", "pageBtn")
        self.btnNextPage.setObjectName("btnNextPage")
        self.btnNextPage.setText(">")
        self.toolbarLayout.addWidget(self.btnNextPage)

        self.tableContainerLayout.addLayout(self.toolbarLayout)

        # Table
        self.tblCustomers = QtWidgets.QTableWidget(parent=self.cardTableContainer)
        self.tblCustomers.setObjectName("tblCustomers")
        self.tblCustomers.setColumnCount(6)
        self.tblCustomers.setRowCount(0)
        self.tableContainerLayout.addWidget(self.tblCustomers)

        # Load More Button
        self.btnLoadMore = QtWidgets.QPushButton(parent=self.cardTableContainer)
        self.btnLoadMore.setMinimumHeight(40)
        self.btnLoadMore.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnLoadMore.setObjectName("btnLoadMore")
        self.tableContainerLayout.addWidget(self.btnLoadMore)

        self.rootLayout.addWidget(self.cardTableContainer, stretch=1)

        self.retranslateUi(CustomerManagement)
        QtCore.QMetaObject.connectSlotsByName(CustomerManagement)

    def retranslateUi(self, CustomerManagement):
        _translate = QtCore.QCoreApplication.translate
        CustomerManagement.setWindowTitle(_translate("CustomerManagement", "Quản lý khách hàng"))
        self.lblTitle.setText(_translate("CustomerManagement", "Quản lý Khách hàng"))
        self.lblSubtitle.setText(_translate("CustomerManagement", "Quản lý thông tin liên lạc, lịch sử mua hàng và cấp độ thành viên."))
        self.btnPurchaseHistory.setText(_translate("CustomerManagement", "  Xem lịch sử mua hàng"))
        self.btnAddCustomer.setText(_translate("CustomerManagement", "  + Thêm khách mới"))
        self.btnEditCustomer.setText(_translate("CustomerManagement", "  Sửa"))
        self.btnDeleteCustomer.setText(_translate("CustomerManagement", "  Xóa"))
        self.lblTotalTitle.setText(_translate("CustomerManagement", "Tổng Thành Viên"))
        self.lblTotalVal.setText(_translate("CustomerManagement", "12,458"))
        self.lblTotalTrend.setText(_translate("CustomerManagement", "↗ +4.2% so với tháng trước"))
        self.lblActiveTitle.setText(_translate("CustomerManagement", "Hoạt động (Tháng này)"))
        self.lblActiveVal.setText(_translate("CustomerManagement", "3,102"))
        self.lblActiveTrend.setText(_translate("CustomerManagement", "25% tỷ lệ giữ chân"))
        self.lblPointsTitle.setText(_translate("CustomerManagement", "Điểm đã phát hành"))
        self.lblPointsVal.setText(_translate("CustomerManagement", "1.2M"))
        self.lblPointsTrend.setText(_translate("CustomerManagement", "↗ +12k tuần này"))
        self.txtSearch.setPlaceholderText(_translate("CustomerManagement", "🔍 Tìm theo tên hoặc SĐT..."))
        self.lblPaginationInfo.setText(_translate("CustomerManagement", "Hiển thị 1-10 của 12,458"))
        self.btnLoadMore.setText(_translate("CustomerManagement", "Tải thêm dữ liệu"))
