# Form implementation generated from reading ui file 'src/gui/customer_picker.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(520, 460)
        Dialog.setStyleSheet("/* ===== Toàn bộ màu sắc của dialog này nằm ở đây =====\n"
"   Sửa trực tiếp trong Qt Designer: chọn Dialog rồi mở styleSheet.\n"
"   Bảng màu lấy đúng theo màn hình POS (pos.ui). */\n"
"\n"
"QDialog {\n"
"    background-color: #f8fafc;\n"
"}\n"
"\n"
"QLabel#lblTitle {\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QLineEdit#txtSearchCustomer {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 6px;\n"
"    padding: 8px 10px;\n"
"    font-size: 13px;\n"
"    color: #0f172a;\n"
"}\n"
"QLineEdit#txtSearchCustomer:focus {\n"
"    border: 1px solid #3b82f6;\n"
"}\n"
"\n"
"QTableWidget#tblCustomers {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #e2e8f0;\n"
"    border-radius: 6px;\n"
"    gridline-color: #f1f5f9;\n"
"    color: #0f172a;\n"
"}\n"
"QTableWidget#tblCustomers::item {\n"
"    padding: 6px;\n"
"}\n"
"QTableWidget#tblCustomers::item:selected {\n"
"    background-color: #dbeafe;\n"
"    color: #0f172a;\n"
"}\n"
"QTableWidget#tblCustomers QHeaderView::section {\n"
"    background-color: #f1f5f9;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    color: #475569;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    font-size: 12px;\n"
"    color: #64748b;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 6px;\n"
"    padding: 8px 16px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#btnSelect {\n"
"    background-color: #2563eb;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"}\n"
"QPushButton#btnSelect:hover {\n"
"    background-color: #1d4ed8;\n"
"}\n"
"QPushButton#btnSelect:disabled {\n"
"    background-color: #cbd5e1;\n"
"    color: #f8fafc;\n"
"}\n"
"\n"
"QPushButton#btnClearCustomer {\n"
"    background-color: #ffffff;\n"
"    color: #b45309;\n"
"    border: 1px solid #fcd34d;\n"
"}\n"
"QPushButton#btnClearCustomer:hover {\n"
"    background-color: #fef3c7;\n"
"}\n"
"\n"
"QPushButton#btnCancel {\n"
"    background-color: #ffffff;\n"
"    color: #475569;\n"
"    border: 1px solid #cbd5e1;\n"
"}\n"
"QPushButton#btnCancel:hover {\n"
"    background-color: #e2e8f0;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(18, 18, 18, 18)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(parent=Dialog)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.txtSearchCustomer = QtWidgets.QLineEdit(parent=Dialog)
        self.txtSearchCustomer.setMinimumSize(QtCore.QSize(0, 38))
        self.txtSearchCustomer.setClearButtonEnabled(True)
        self.txtSearchCustomer.setObjectName("txtSearchCustomer")
        self.verticalLayout.addWidget(self.txtSearchCustomer)
        self.tblCustomers = QtWidgets.QTableWidget(parent=Dialog)
        self.tblCustomers.setStyleSheet("QTableWidget::item {\n"
"    padding: 8px 12px;\n"
"    border-bottom: 1px solid #f1f5f9;\n"
"    color: #1e293b;\n"
"    outline: none; \n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #f8fafc;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #eff6ff;\n"
"    color: #1d4ed8;         \n"
"    font-weight: 600;\n"
"}")
        self.tblCustomers.setAlternatingRowColors(False)
        self.tblCustomers.setShowGrid(False)
        self.tblCustomers.setObjectName("tblCustomers")
        self.tblCustomers.setColumnCount(0)
        self.tblCustomers.setRowCount(0)
        self.verticalLayout.addWidget(self.tblCustomers)
        self.lblStatus = QtWidgets.QLabel(parent=Dialog)
        self.lblStatus.setText("")
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout.addWidget(self.lblStatus)
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setSpacing(10)
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        self.btnClearCustomer = QtWidgets.QPushButton(parent=Dialog)
        self.btnClearCustomer.setMinimumSize(QtCore.QSize(0, 38))
        self.btnClearCustomer.setStyleSheet("QPushButton {\n"
"    background-color: #f1f5f9;\n"
"    color: #475569;\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e2e8f0;\n"
"    color: #1e293b;\n"
"    border-color: #94a3b8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #cbd5e1;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #f8fafc;\n"
"    color: #cbd5e1;\n"
"    border-color: #e2e8f0;\n"
"}")
        self.btnClearCustomer.setObjectName("btnClearCustomer")
        self.horizontalLayout_buttons.addWidget(self.btnClearCustomer)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_buttons.addItem(spacerItem)
        self.btnCancel = QtWidgets.QPushButton(parent=Dialog)
        self.btnCancel.setMinimumSize(QtCore.QSize(90, 38))
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_buttons.addWidget(self.btnCancel)
        self.btnSelect = QtWidgets.QPushButton(parent=Dialog)
        self.btnSelect.setMinimumSize(QtCore.QSize(110, 38))
        self.btnSelect.setObjectName("btnSelect")
        self.horizontalLayout_buttons.addWidget(self.btnSelect)
        self.verticalLayout.addLayout(self.horizontalLayout_buttons)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Chọn khách hàng"))
        self.lblTitle.setText(_translate("Dialog", "Chọn khách hàng cho hóa đơn"))
        self.txtSearchCustomer.setPlaceholderText(_translate("Dialog", "Tìm theo tên hoặc số điện thoại..."))
        self.btnClearCustomer.setToolTip(_translate("Dialog", "Gỡ khách khỏi hóa đơn, quay lại Khách lẻ"))
        self.btnClearCustomer.setText(_translate("Dialog", "Bỏ chọn (Khách lẻ)"))
        self.btnCancel.setText(_translate("Dialog", "Hủy"))
        self.btnSelect.setText(_translate("Dialog", "Chọn khách"))
