# Form implementation generated from reading ui file 'src/gui/customer_form_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_CustomerFormDialog(object):
    def setupUi(self, CustomerFormDialog):
        CustomerFormDialog.setObjectName("CustomerFormDialog")
        CustomerFormDialog.resize(440, 300)
        CustomerFormDialog.setStyleSheet("""
/* ===== Dialog Thêm / Sửa khách hàng ===== */
QDialog#CustomerFormDialog {
    background-color: #ffffff;
    font-family: "Segoe UI", Arial, sans-serif;
}

QLabel {
    color: #1e293b;
    font-size: 13px;
    font-family: "Segoe UI", Arial, sans-serif;
}

QLineEdit, QDateEdit {
    background-color: #ffffff;
    border: 1px solid #e2e8f0;
    border-radius: 8px;
    padding: 4px 12px;
    font-size: 13px;
    font-family: "Segoe UI", Arial, sans-serif;
    color: #0f172a;
}
QLineEdit:focus, QDateEdit:focus {
    border: 1px solid #1d4ed8;
}

QPushButton#btnCancel {
    background-color: #f1f5f9;
    color: #64748b;
    border: 1px solid #e2e8f0;
    border-radius: 8px;
    font-size: 13px;
    font-weight: bold;
}
QPushButton#btnCancel:hover {
    background-color: #e2e8f0;
}

QPushButton#btnSave {
    background-color: #1d4ed8;
    color: #ffffff;
    border: none;
    border-radius: 8px;
    font-size: 13px;
    font-weight: bold;
}
QPushButton#btnSave:hover {
    background-color: #1e3a8a;
}

QPushButton#chkNoDob {
    background-color: #f1f5f9;
    border: 1px solid #e2e8f0;
    border-radius: 6px;
    padding: 4px 12px;
    font-size: 12px;
    color: #475569;
}
QPushButton#chkNoDob:checked {
    background-color: #dbeafe;
    border: 1px solid #3b82f6;
    color: #1d4ed8;
}
""")
        self.rootLayout = QtWidgets.QVBoxLayout(CustomerFormDialog)
        self.rootLayout.setContentsMargins(24, 20, 24, 20)
        self.rootLayout.setSpacing(16)
        self.rootLayout.setObjectName("rootLayout")

        self.lblDialogTitle = QtWidgets.QLabel(parent=CustomerFormDialog)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        self.lblDialogTitle.setFont(font)
        self.lblDialogTitle.setObjectName("lblDialogTitle")
        self.rootLayout.addWidget(self.lblDialogTitle)

        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSpacing(12)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.formLayout.setObjectName("formLayout")

        self.lblFieldName = QtWidgets.QLabel(parent=CustomerFormDialog)
        self.lblFieldName.setObjectName("lblFieldName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFieldName)

        self.txtName = QtWidgets.QLineEdit(parent=CustomerFormDialog)
        self.txtName.setMinimumHeight(36)
        self.txtName.setObjectName("txtName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtName)

        self.lblFieldPhone = QtWidgets.QLabel(parent=CustomerFormDialog)
        self.lblFieldPhone.setObjectName("lblFieldPhone")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFieldPhone)

        self.txtPhone = QtWidgets.QLineEdit(parent=CustomerFormDialog)
        self.txtPhone.setMinimumHeight(36)
        self.txtPhone.setObjectName("txtPhone")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtPhone)

        self.lblFieldDob = QtWidgets.QLabel(parent=CustomerFormDialog)
        self.lblFieldDob.setObjectName("lblFieldDob")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFieldDob)

        self.dobLayout = QtWidgets.QHBoxLayout()
        self.dobLayout.setSpacing(8)
        self.dobLayout.setObjectName("dobLayout")

        self.dateDob = QtWidgets.QDateEdit(parent=CustomerFormDialog)
        self.dateDob.setMinimumHeight(36)
        self.dateDob.setCalendarPopup(True)
        self.dateDob.setDisplayFormat("dd/MM/yyyy")
        self.dateDob.setDate(QtCore.QDate(2000, 1, 1))
        self.dateDob.setObjectName("dateDob")
        self.dobLayout.addWidget(self.dateDob)

        self.chkNoDob = QtWidgets.QPushButton(parent=CustomerFormDialog)
        self.chkNoDob.setMinimumHeight(36)
        self.chkNoDob.setCheckable(True)
        self.chkNoDob.setChecked(True)
        self.chkNoDob.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.chkNoDob.setObjectName("chkNoDob")
        self.dobLayout.addWidget(self.chkNoDob)

        self.formLayout.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dobLayout)
        self.rootLayout.addLayout(self.formLayout)

        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.rootLayout.addItem(spacerItem)

        self.btnLayout = QtWidgets.QHBoxLayout()
        self.btnLayout.setSpacing(10)
        self.btnLayout.setObjectName("btnLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.btnLayout.addItem(spacerItem1)

        self.btnCancel = QtWidgets.QPushButton(parent=CustomerFormDialog)
        self.btnCancel.setMinimumSize(QtCore.QSize(100, 40))
        self.btnCancel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCancel.setObjectName("btnCancel")
        self.btnLayout.addWidget(self.btnCancel)

        self.btnSave = QtWidgets.QPushButton(parent=CustomerFormDialog)
        self.btnSave.setMinimumSize(QtCore.QSize(120, 40))
        self.btnSave.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnSave.setObjectName("btnSave")
        self.btnLayout.addWidget(self.btnSave)

        self.rootLayout.addLayout(self.btnLayout)

        self.retranslateUi(CustomerFormDialog)
        QtCore.QMetaObject.connectSlotsByName(CustomerFormDialog)

    def retranslateUi(self, CustomerFormDialog):
        _translate = QtCore.QCoreApplication.translate
        CustomerFormDialog.setWindowTitle(_translate("CustomerFormDialog", "Thông tin khách hàng"))
        self.lblDialogTitle.setText(_translate("CustomerFormDialog", "Thêm khách hàng mới"))
        self.lblFieldName.setText(_translate("CustomerFormDialog", "Họ tên *: "))
        self.txtName.setPlaceholderText(_translate("CustomerFormDialog", "Nhập họ tên khách hàng"))
        self.lblFieldPhone.setText(_translate("CustomerFormDialog", "Số điện thoại *: "))
        self.txtPhone.setPlaceholderText(_translate("CustomerFormDialog", "Nhập số điện thoại"))
        self.lblFieldDob.setText(_translate("CustomerFormDialog", "Ngày sinh: "))
        self.chkNoDob.setText(_translate("CustomerFormDialog", "Không có"))
        self.btnCancel.setText(_translate("CustomerFormDialog", "Hủy"))
        self.btnSave.setText(_translate("CustomerFormDialog", "Lưu"))
