# Form implementation generated from reading ui file 'src/gui/discount_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_DiscountDialog(object):
    def setupUi(self, DiscountDialog):
        DiscountDialog.setObjectName("DiscountDialog")
        DiscountDialog.resize(320, 178)
        DiscountDialog.setStyleSheet("QDialog {\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QLabel#lblTitle {\n"
"    color: #0f172a;\n"
"    font-size: 15px;\n"
"    font-weight: 600;\n"
"    padding: 2px 0;\n"
"}\n"
"\n"
"QDoubleSpinBox#spnDiscount {\n"
"    background-color: #ffffff;\n"
"    color: #0f172a;\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"    selection-background-color: #2563eb;\n"
"    selection-color: #ffffff;\n"
"}\n"
"\n"
"QDoubleSpinBox#spnDiscount:hover {\n"
"    border: 1px solid #94a3b8;\n"
"}\n"
"\n"
"QDoubleSpinBox#spnDiscount:focus {\n"
"    border: 1px solid #2563eb;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QDoubleSpinBox#spnDiscount::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border: none;\n"
"    border-top-right-radius: 7px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QDoubleSpinBox#spnDiscount::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"    width: 20px;\n"
"    border: none;\n"
"    border-bottom-right-radius: 7px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QDoubleSpinBox#spnDiscount::up-arrow {\n"
"    width: 0;\n"
"    height: 0;\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-bottom: 5px solid #64748b;\n"
"}\n"
"\n"
"QDoubleSpinBox#spnDiscount::down-arrow {\n"
"    width: 0;\n"
"    height: 0;\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-top: 5px solid #64748b;\n"
"}\n"
"\n"
"QDoubleSpinBox#spnDiscount::up-button:hover,\n"
"QDoubleSpinBox#spnDiscount::down-button:hover {\n"
"    background-color: #f1f5f9;\n"
"}\n"
"\n"
"QPushButton#btnApply {\n"
"    background-color: #2563eb;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px 18px;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton#btnApply:hover {\n"
"    background-color: #1d4ed8;\n"
"}\n"
"\n"
"QPushButton#btnApply:pressed {\n"
"    background-color: #1e40af;\n"
"}\n"
"\n"
"QPushButton#btnApply:disabled {\n"
"    background-color: #cbd5e1;\n"
"    color: #94a3b8;\n"
"}\n"
"\n"
"QPushButton#btnCancel {\n"
"    background-color: #f8fafc;\n"
"    color: #475569;\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 8px;\n"
"    padding: 8px 18px;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QPushButton#btnCancel:hover {\n"
"    background-color: #f1f5f9;\n"
"    border: 1px solid #94a3b8;\n"
"    color: #334155;\n"
"}\n"
"\n"
"QPushButton#btnCancel:pressed {\n"
"    background-color: #e2e8f0;\n"
"}\n"
"\n"
"QPushButton#btnCancel:disabled {\n"
"    background-color: #f8fafc;\n"
"    color: #94a3b8;\n"
"    border: 1px solid #e2e8f0;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(DiscountDialog)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(parent=DiscountDialog)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.spnDiscount = QtWidgets.QDoubleSpinBox(parent=DiscountDialog)
        self.spnDiscount.setStyleSheet("QDoubleSpinBox {\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-size: 14px;\n"
"    color: #0f172a;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QDoubleSpinBox:focus {\n"
"    border: 1px solid #2563eb;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button, \n"
"QDoubleSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    width: 22px;\n"
"    background-color: #f1f5f9;\n"
"    border-left: 1px solid #cbd5e1;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button {\n"
"    subcontrol-position: top right;\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-arrow {\n"
"    image: none;\n"
"    width: 0;\n"
"    height: 0;\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-bottom: 5px solid #475569; \n"
"}\n"
"\n"
"QDoubleSpinBox::down-button {\n"
"    subcontrol-position: bottom right;\n"
"    border-bottom-right-radius: 5px;\n"
"    border-top: 1px solid #cbd5e1;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-arrow {\n"
"    image: none;\n"
"    width: 0;\n"
"    height: 0;\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-top: 5px solid #475569; \n"
"}\n"
"\n"
"QDoubleSpinBox::up-button:hover, \n"
"QDoubleSpinBox::down-button:hover {\n"
"    background-color: #e2e8f0;\n"
"}")
        self.spnDiscount.setDecimals(1)
        self.spnDiscount.setMaximum(100.0)
        self.spnDiscount.setObjectName("spnDiscount")
        self.verticalLayout.addWidget(self.spnDiscount)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnCancel = QtWidgets.QPushButton(parent=DiscountDialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.btnApply = QtWidgets.QPushButton(parent=DiscountDialog)
        self.btnApply.setObjectName("btnApply")
        self.horizontalLayout.addWidget(self.btnApply)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DiscountDialog)
        QtCore.QMetaObject.connectSlotsByName(DiscountDialog)

    def retranslateUi(self, DiscountDialog):
        _translate = QtCore.QCoreApplication.translate
        DiscountDialog.setWindowTitle(_translate("DiscountDialog", "Giảm giá hóa đơn"))
        self.lblTitle.setText(_translate("DiscountDialog", "Nhập mức giảm giá (%):"))
        self.btnCancel.setText(_translate("DiscountDialog", "Hủy"))
        self.btnApply.setText(_translate("DiscountDialog", "Áp dụng"))
