# Form implementation generated from reading ui file 'src/gui/forgot_password.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 680)
        MainWindow.setStyleSheet("#centralwidget {\n"
"    background-color: #f3f4f6;\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.forgot_card = QtWidgets.QFrame(parent=self.centralwidget)
        self.forgot_card.setMinimumSize(QtCore.QSize(420, 470))
        self.forgot_card.setMaximumSize(QtCore.QSize(420, 470))
        self.forgot_card.setStyleSheet("/* ===== Toàn bộ màu sắc của màn hình này nằm ở đây =====\n"
"   Sửa trực tiếp trong Qt Designer: chọn khung forgot_card rồi mở styleSheet.\n"
"   Bảng màu lấy đúng theo form Đăng nhập (login.ui). */\n"
"\n"
"#forgot_card {\n"
"    background-color: #ffffff;\n"
"    border-radius: 12px;\n"
"    border: 1px solid #e5e7eb;\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Tên hệ thống */\n"
"#lblTitle {\n"
"    color: #0c2b82;\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Dòng mô tả dưới tên hệ thống */\n"
"#lblSubtitle {\n"
"    color: #6b7280;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* Đường kẻ ngăn cách */\n"
"#dividerLine {\n"
"    background-color: #e5e7eb;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Nhãn đứng trên ô nhập */\n"
"#lblField {\n"
"    color: #374151;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#lblCopyright {\n"
"    color: #9ca3af;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #d1d5db;\n"
"    border-radius: 6px;\n"
"    padding: 0px 12px;\n"
"    background-color: #ffffff;\n"
"    color: #111827;\n"
"    font-size: 13px;\n"
"    selection-background-color: #0c2b82;\n"
"    selection-color: #ffffff;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0c2b82;\n"
"}\n"
"\n"
"/* Nút chính */\n"
"#pushButton_accept {\n"
"    background-color: #002b9a;\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"#pushButton_accept:hover {\n"
"    background-color: #00227b;\n"
"}\n"
"\n"
"#pushButton_accept:pressed {\n"
"    background-color: #001857;\n"
"}\n"
"\n"
"#pushButton_accept:disabled {\n"
"    background-color: #9ca3af;\n"
"}\n"
"\n"
"/* Nút dạng liên kết */\n"
"#pushButton_2 {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #0c2b82;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"#pushButton_2:hover {\n"
"    color: #081d59;\n"
"    text-decoration: underline;\n"
"}")
        self.forgot_card.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.forgot_card.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.forgot_card.setObjectName("forgot_card")
        self.lblLogo = QtWidgets.QLabel(parent=self.forgot_card)
        self.lblLogo.setGeometry(QtCore.QRect(140, 21, 140, 100))
        self.lblLogo.setMinimumSize(QtCore.QSize(140, 100))
        self.lblLogo.setMaximumSize(QtCore.QSize(140, 100))
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap("src/gui\\../../assets/images/logo.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.lblTitle = QtWidgets.QLabel(parent=self.forgot_card)
        self.lblTitle.setGeometry(QtCore.QRect(10, 121, 401, 30))
        self.lblTitle.setMinimumSize(QtCore.QSize(0, 30))
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.lblSubtitle = QtWidgets.QLabel(parent=self.forgot_card)
        self.lblSubtitle.setGeometry(QtCore.QRect(10, 151, 401, 21))
        self.lblSubtitle.setMinimumSize(QtCore.QSize(0, 21))
        self.lblSubtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.dividerLine = QtWidgets.QFrame(parent=self.forgot_card)
        self.dividerLine.setGeometry(QtCore.QRect(40, 195, 341, 1))
        self.dividerLine.setMinimumSize(QtCore.QSize(0, 1))
        self.dividerLine.setMaximumSize(QtCore.QSize(16777215, 1))
        self.dividerLine.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.dividerLine.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.dividerLine.setObjectName("dividerLine")
        self.lblField = QtWidgets.QLabel(parent=self.forgot_card)
        self.lblField.setGeometry(QtCore.QRect(40, 215, 35, 24))
        self.lblField.setMinimumSize(QtCore.QSize(0, 24))
        self.lblField.setObjectName("lblField")
        self.lineEdit_email = QtWidgets.QLineEdit(parent=self.forgot_card)
        self.lineEdit_email.setGeometry(QtCore.QRect(40, 239, 341, 42))
        self.lineEdit_email.setMinimumSize(QtCore.QSize(0, 42))
        self.lineEdit_email.setMaximumSize(QtCore.QSize(16777215, 42))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.pushButton_accept = QtWidgets.QPushButton(parent=self.forgot_card)
        self.pushButton_accept.setGeometry(QtCore.QRect(40, 320, 341, 61))
        self.pushButton_accept.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_accept.setMaximumSize(QtCore.QSize(16777215, 61))
        self.pushButton_accept.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.forgot_card)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 379, 341, 51))
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lblCopyright = QtWidgets.QLabel(parent=self.forgot_card)
        self.lblCopyright.setGeometry(QtCore.QRect(38, 409, 351, 51))
        self.lblCopyright.setMinimumSize(QtCore.QSize(0, 20))
        self.lblCopyright.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCopyright.setObjectName("lblCopyright")
        self.gridLayout.addWidget(self.forgot_card, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RetailPro ERP / Quên mật khẩu"))
        self.lblTitle.setText(_translate("MainWindow", "RetailPro ERP"))
        self.lblSubtitle.setText(_translate("MainWindow", "Nhập email đã đăng ký để nhận mã xác thực"))
        self.lblField.setText(_translate("MainWindow", "Email:"))
        self.lineEdit_email.setPlaceholderText(_translate("MainWindow", "email@example.com"))
        self.pushButton_accept.setText(_translate("MainWindow", "Gửi mã xác thực"))
        self.pushButton_2.setText(_translate("MainWindow", "Quay lại đăng nhập"))
        self.lblCopyright.setText(_translate("MainWindow", "Copyright © 2026 RetailPro ERP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
