# Form implementation generated from reading ui file 'D:\Python\Supermarket_Manager\Supermarket_Manager\src\gui\forgotpassword.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 674)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: #f0f4f8; /* Màu nền tổng thể */\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.widget)
        self.frame.setMaximumSize(QtCore.QSize(400, 500))
        self.frame.setStyleSheet("#frame {\n"
"    background-color: white;\n"
"    border-radius: 8px;\n"
"    border: 1px solid #e2e8f0;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setStyleSheet("#frame_2{\n"
"         background-color: white;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(60, 60))
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setStyleSheet("background-color: transparent;\n"
"border: none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Python\\Supermarket_Manager\\Supermarket_Manager\\src\\gui\\../../assets/images/logo.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setStyleSheet("background-color: transparent;\n"
"border: none;\n"
"color: #0c2b82;      /* Màu chữ xanh đậm */\n"
"font-size: 24px;     /* Kích thước chữ to */\n"
"font-weight: bold;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setStyleSheet("background-color: transparent;\n"
"border: none;\n"
"color: #000000;\n"
"font-size: 15px;\n"
"font-weight: bold;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_4.setStyleSheet("#label_4{\n"
"     background-color: white;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Arial,sans-serif")
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("#label_5{\n"
"         background-color: white;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.lineEdit_email = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_email.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 4px;\n"
"    padding: 8px;\n"
"    background-color: #ffffff; /* Đổi nền xám thành trắng */\n"
"}")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.verticalLayout_2.addWidget(self.lineEdit_email)
        self.pushButton_glket = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_glket.setStyleSheet("QPushButton {\n"
"    background-color: #0c2b82; /* Màu xanh đậm */\n"
"    color: white;              /* Chữ màu trắng */\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    border-radius: 4px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #081d59; /* Đậm hơn chút khi di chuột vào */\n"
"}")
        self.pushButton_glket.setObjectName("pushButton_glket")
        self.verticalLayout_2.addWidget(self.pushButton_glket)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Xóa nền */\n"
"    border: none;                  /* Xóa viền */\n"
"    color: #0c2b82;                /* Màu xanh đậm giống thiết kế */\n"
"    font-weight: bold;             /* In đậm */\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* Hiệu ứng: Khi di chuột vào sẽ xuất hiện gạch chân để giống Link */\n"
"QPushButton:hover {\n"
"    text-decoration: underline; \n"
"    color: #081d59;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 953, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "RetailPro ERP"))
        self.label_3.setText(_translate("MainWindow", "QUÊN MẬT KHẨU"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Vui lòng nhập địa chỉ email đã đăng ký để</p><p align=\"center\">nhận liên kết đặt lại mật khẩu.</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Email"))
        self.lineEdit_email.setPlaceholderText(_translate("MainWindow", " nhanvie@gmail.com"))
        self.pushButton_glket.setText(_translate("MainWindow", "Gửi liên kết đặt lại ->"))
        self.pushButton_2.setText(_translate("MainWindow", "⟵ Quay lại đăng nhập"))
