# Form implementation generated from reading ui file 'D:\Python\Supermarket_Manager\src\gui\login.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1001, 593)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #f0f4f8; /* Màu nền tổng thể */\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.login_card = QtWidgets.QFrame(parent=self.centralwidget)
        self.login_card.setMinimumSize(QtCore.QSize(400, 500))
        self.login_card.setMaximumSize(QtCore.QSize(400, 500))
        self.login_card.setStyleSheet("#login_card {\n"
"    background-color: white;\n"
"    border-radius: 8px;\n"
"    border: 1px solid #e2e8f0;\n"
"}")
        self.login_card.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.login_card.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.login_card.setObjectName("login_card")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.login_card)
        self.verticalLayout_2.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(parent=self.login_card)
        self.label_4.setMaximumSize(QtCore.QSize(60, 60))
        self.label_4.setStyleSheet("background-color: transparent;\n"
"border: none;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:\\Python\\Supermarket_Manager\\src\\gui\\../../assets/images/logo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(parent=self.login_card)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Arial,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: transparent;\n"
"border: none;\n"
"color: #0c2b82;      /* Màu chữ xanh đậm */\n"
"font-size: 24px;     /* Kích thước chữ to */\n"
"font-weight: bold;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(parent=self.login_card)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Arial,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: transparent;\n"
"border: none;\n"
"color: #000000;\n"
"font-size: 15px;\n"
"font-weight: bold;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(parent=self.login_card)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Arial,sans-serif")
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: transparent;\n"
"border: none;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_5 = QtWidgets.QLabel(parent=self.login_card)
        self.label_5.setStyleSheet("background-color: transparent;\n"
"border: none;\n"
"color: #475569;      /* Màu xám tinh tế */\n"
"font-size: 12px;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lineEdit_username = QtWidgets.QLineEdit(parent=self.login_card)
        self.lineEdit_username.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 4px;\n"
"    padding: 8px;\n"
"    background-color: #ffffff; /* Đổi nền xám thành trắng */\n"
"}")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.verticalLayout.addWidget(self.lineEdit_username)
        self.label_6 = QtWidgets.QLabel(parent=self.login_card)
        self.label_6.setStyleSheet("background-color: transparent;\n"
"border: none;\n"
"color: #475569;      /* Màu xám tinh tế */\n"
"font-size: 12px;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.lineEdit_passwprd = QtWidgets.QLineEdit(parent=self.login_card)
        self.lineEdit_passwprd.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 4px;\n"
"    padding: 8px;\n"
"    background-color: #ffffff; /* Đổi nền xám thành trắng */\n"
"}")
        self.lineEdit_passwprd.setObjectName("lineEdit_passwprd")
        self.verticalLayout.addWidget(self.lineEdit_passwprd)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(parent=self.login_card)
        self.checkBox.setStyleSheet("background-color: transparent;\n"
"border: none;")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_forgotpassword = QtWidgets.QPushButton(parent=self.login_card)
        self.pushButton_forgotpassword.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_forgotpassword.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Xóa nền */\n"
"    border: none;                  /* Xóa viền */\n"
"    color: #0c2b82;                /* Màu xanh đậm giống thiết kế */\n"
"    font-weight: bold;             /* In đậm */\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* Hiệu ứng: Khi di chuột vào sẽ xuất hiện gạch chân để giống Link */\n"
"QPushButton:hover {\n"
"    text-decoration: underline; \n"
"    color: #081d59;\n"
"}")
        self.pushButton_forgotpassword.setObjectName("pushButton_forgotpassword")
        self.horizontalLayout_3.addWidget(self.pushButton_forgotpassword)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.pushButton_login = QtWidgets.QPushButton(parent=self.login_card)
        self.pushButton_login.setStyleSheet("QPushButton {\n"
"    background-color: #0c2b82; /* Màu xanh đậm */\n"
"    color: white;              /* Chữ màu trắng */\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    border-radius: 4px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #081d59; /* Đậm hơn chút khi di chuột vào */\n"
"}")
        self.pushButton_login.setObjectName("pushButton_login")
        self.verticalLayout.addWidget(self.pushButton_login)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.login_card, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1001, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "RetailPro ERP"))
        self.label_2.setText(_translate("MainWindow", "Đăng nhập hệ thống"))
        self.label.setText(_translate("MainWindow", "Vui lòng nhập thông tin để truy cập quản trị"))
        self.label_5.setText(_translate("MainWindow", "TÊN ĐĂNG NHẬP"))
        self.label_6.setText(_translate("MainWindow", "MẬT KHẨU"))
        self.checkBox.setText(_translate("MainWindow", "Ghi nhớ đăng nhập"))
        self.pushButton_forgotpassword.setText(_translate("MainWindow", "Quên mật khẩu ?"))
        self.pushButton_login.setText(_translate("MainWindow", "Đăng nhập"))
