# Form implementation generated from reading ui file 'src/gui/login.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 680)
        MainWindow.setStyleSheet("#centralwidget {\n"
"    background-color: #f3f4f6;\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.login_card = QtWidgets.QFrame(parent=self.centralwidget)
        self.login_card.setMinimumSize(QtCore.QSize(420, 520))
        self.login_card.setMaximumSize(QtCore.QSize(420, 520))
        self.login_card.setStyleSheet("#login_card {\n"
"    background-color: #ffffff;\n"
"    border-radius: 12px;\n"
"    border: 1px solid #e5e7eb;\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #d1d5db;\n"
"    border-radius: 6px;\n"
"    padding: 0px 12px;\n"
"    background-color: #ffffff;\n"
"    color: #111827;\n"
"    font-size: 13px;\n"
"    selection-background-color: #0c2b82;\n"
"    selection-color: #ffffff;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0c2b82;\n"
"}\n"
"\n"
"/* Nút con mắt ẩn/hiện mật khẩu nằm bên trong ô mật khẩu */\n"
"QToolButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    padding: 0px;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    background-color: transparent;\n"
"    color: #4b5563;\n"
"    font-size: 13px;\n"
"    spacing: 8px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: 1px solid #d1d5db;\n"
"    border-radius: 4px;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border-color: #0c2b82;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #0c2b82;\n"
"    border-color: #0c2b82;\n"
"    image: url(assets/images/check.png);\n"
"}\n"
"\n"
"#pushButton_forgotpassword {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #0c2b82;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"#pushButton_forgotpassword:hover {\n"
"    color: #081d59;\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"#pushButton_login {\n"
"    background-color: #002b9a;\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"#pushButton_login:hover {\n"
"    background-color: #00227b;\n"
"}\n"
"\n"
"#pushButton_login:pressed {\n"
"    background-color: #001857;\n"
"}")
        self.login_card.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.login_card.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.login_card.setObjectName("login_card")
        self.label_4 = QtWidgets.QLabel(parent=self.login_card)
        self.label_4.setGeometry(QtCore.QRect(140, 10, 140, 100))
        self.label_4.setMinimumSize(QtCore.QSize(140, 100))
        self.label_4.setMaximumSize(QtCore.QSize(17, 17))
        self.label_4.setStyleSheet("background-color: transparent; border: none;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("src/gui\\../../assets/images/logo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.login_card)
        self.label_3.setGeometry(QtCore.QRect(140, 100, 140, 30))
        self.label_3.setStyleSheet("color: #0c2b82; font-size: 22px; font-weight: bold;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(parent=self.login_card)
        self.label.setGeometry(QtCore.QRect(80, 130, 253, 21))
        self.label.setStyleSheet("color: #6b7280; font-size: 13px;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.dividerLine = QtWidgets.QFrame(parent=self.login_card)
        self.dividerLine.setGeometry(QtCore.QRect(41, 174, 340, 1))
        self.dividerLine.setMinimumSize(QtCore.QSize(0, 1))
        self.dividerLine.setMaximumSize(QtCore.QSize(16777215, 1))
        self.dividerLine.setStyleSheet("background-color: #e5e7eb; border: none;")
        self.dividerLine.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.dividerLine.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.dividerLine.setObjectName("dividerLine")
        self.label_5 = QtWidgets.QLabel(parent=self.login_card)
        self.label_5.setGeometry(QtCore.QRect(40, 190, 91, 31))
        self.label_5.setStyleSheet("color: #374151; font-size: 13px; font-weight: 600;")
        self.label_5.setObjectName("label_5")
        self.lineEdit_username = QtWidgets.QLineEdit(parent=self.login_card)
        self.lineEdit_username.setGeometry(QtCore.QRect(40, 220, 341, 42))
        self.lineEdit_username.setMinimumSize(QtCore.QSize(0, 42))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.label_6 = QtWidgets.QLabel(parent=self.login_card)
        self.label_6.setGeometry(QtCore.QRect(40, 270, 59, 31))
        self.label_6.setStyleSheet("color: #374151; font-size: 13px; font-weight: 600;")
        self.label_6.setObjectName("label_6")
        self.lineEdit_passwprd = QtWidgets.QLineEdit(parent=self.login_card)
        self.lineEdit_passwprd.setGeometry(QtCore.QRect(40, 300, 341, 42))
        self.lineEdit_passwprd.setMinimumSize(QtCore.QSize(0, 42))
        self.lineEdit_passwprd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_passwprd.setObjectName("lineEdit_passwprd")
        self.pushButton_login = QtWidgets.QPushButton(parent=self.login_card)
        self.pushButton_login.setGeometry(QtCore.QRect(40, 400, 341, 61))
        self.pushButton_login.setMinimumSize(QtCore.QSize(0, 44))
        self.pushButton_login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_login.setObjectName("pushButton_login")
        self.lblCopyright = QtWidgets.QLabel(parent=self.login_card)
        self.lblCopyright.setGeometry(QtCore.QRect(130, 470, 169, 41))
        self.lblCopyright.setStyleSheet("color: #9ca3af; font-size: 12px;")
        self.lblCopyright.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCopyright.setObjectName("lblCopyright")
        self.layoutWidget = QtWidgets.QWidget(parent=self.login_card)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 350, 341, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(2, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(parent=self.layoutWidget)
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_forgotpassword = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_forgotpassword.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_forgotpassword.setObjectName("pushButton_forgotpassword")
        self.horizontalLayout_3.addWidget(self.pushButton_forgotpassword)
        self.gridLayout.addWidget(self.login_card, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RetailPro ERP / Đăng nhập"))
        self.label_3.setText(_translate("MainWindow", "RetailPro ERP"))
        self.label.setText(_translate("MainWindow", "Vui lòng nhập thông tin để truy cập quản trị"))
        self.label_5.setText(_translate("MainWindow", "Tên đăng nhập:"))
        self.lineEdit_username.setPlaceholderText(_translate("MainWindow", "Email hoặc tên đăng nhập"))
        self.label_6.setText(_translate("MainWindow", "Mật khẩu:"))
        self.lineEdit_passwprd.setPlaceholderText(_translate("MainWindow", "••••••••"))
        self.pushButton_login.setText(_translate("MainWindow", "Đăng nhập"))
        self.lblCopyright.setText(_translate("MainWindow", "Copyright © 2026 RetailPro ERP"))
        self.checkBox.setText(_translate("MainWindow", "Ghi nhớ tôi"))
        self.pushButton_forgotpassword.setText(_translate("MainWindow", "Quên mật khẩu?"))
