# Form implementation generated from reading ui file 'D:\Python\Supermarket_Manager\src\gui\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1653, 983)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.sidebar_frame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.sidebar_frame.setStyleSheet("#sidebar_frame {\n"
"    background-color: #334155; \n"
"}\n"
"\n"
"/* 2. Định dạng các nút bấm */\n"
"#sidebar_frame QPushButton {\n"
"    color: #cbd5e1;                \n"
"    text-align: left;              \n"
"    padding: 10px 10px 10px 30px;  \n"
"    border: none;                  \n"
"    font-size: 13px;               \n"
"    font-weight: bold;             \n"
"}\n"
"\n"
"/* 3. Hiệu ứng Hover cho nút */\n"
"#sidebar_frame QPushButton:hover {\n"
"    background-color: #475569;     \n"
"    color: #ffffff;                \n"
"    border-left: 4px solid #3b82f6;\n"
"}\n"
"\n"
"/* 4. Đổi màu chữ Logo và Tiêu đề thành trắng cho nổi bật */\n"
"#sidebar_frame QLabel {\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"}")
        self.sidebar_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sidebar_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sidebar_frame.setObjectName("sidebar_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sidebar_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.sidebar_frame)
        self.frame.setStyleSheet("#frame {\n"
"    background-color: #334155;\n"
"    border: none; \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setMaximumSize(QtCore.QSize(70, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Python\\Supermarket_Manager\\src\\gui\\../../assets/images/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setStyleSheet("#frame_2 {\n"
"    background-color: #334155;\n"
"    border: none;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.frame)
        self.btn_dashboard = QtWidgets.QPushButton(parent=self.sidebar_frame)
        self.btn_dashboard.setObjectName("btn_dashboard")
        self.verticalLayout_2.addWidget(self.btn_dashboard)
        self.btn_products = QtWidgets.QPushButton(parent=self.sidebar_frame)
        self.btn_products.setObjectName("btn_products")
        self.verticalLayout_2.addWidget(self.btn_products)
        self.btn_suppliers = QtWidgets.QPushButton(parent=self.sidebar_frame)
        self.btn_suppliers.setObjectName("btn_suppliers")
        self.verticalLayout_2.addWidget(self.btn_suppliers)
        self.btn_importing = QtWidgets.QPushButton(parent=self.sidebar_frame)
        self.btn_importing.setObjectName("btn_importing")
        self.verticalLayout_2.addWidget(self.btn_importing)
        self.btn_customers = QtWidgets.QPushButton(parent=self.sidebar_frame)
        self.btn_customers.setObjectName("btn_customers")
        self.verticalLayout_2.addWidget(self.btn_customers)
        self.btn_pos = QtWidgets.QPushButton(parent=self.sidebar_frame)
        self.btn_pos.setObjectName("btn_pos")
        self.verticalLayout_2.addWidget(self.btn_pos)
        self.btn_analytics = QtWidgets.QPushButton(parent=self.sidebar_frame)
        self.btn_analytics.setObjectName("btn_analytics")
        self.verticalLayout_2.addWidget(self.btn_analytics)
        self.btn_settings = QtWidgets.QPushButton(parent=self.sidebar_frame)
        self.btn_settings.setObjectName("btn_settings")
        self.verticalLayout_2.addWidget(self.btn_settings)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.frame_3 = QtWidgets.QFrame(parent=self.sidebar_frame)
        self.frame_3.setStyleSheet("#frame_3 {\n"
"    background-color: #334155;\n"
"    border: none; \n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_help = QtWidgets.QPushButton(parent=self.frame_3)
        self.btn_help.setObjectName("btn_help")
        self.verticalLayout_3.addWidget(self.btn_help)
        self.btn_logout = QtWidgets.QPushButton(parent=self.frame_3)
        self.btn_logout.setObjectName("btn_logout")
        self.verticalLayout_3.addWidget(self.btn_logout)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.sidebar_frame)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_2.setStyleSheet("#widget_2 {\n"
"    background-color: #ffffff; \n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(20, 20, 20, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblDateTime = QtWidgets.QLabel(parent=self.widget_2)
        self.lblDateTime.setObjectName("lblDateTime")
        self.horizontalLayout_2.addWidget(self.lblDateTime)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lblGreeting = QtWidgets.QLabel(parent=self.widget_2)
        self.lblGreeting.setObjectName("lblGreeting")
        self.horizontalLayout_2.addWidget(self.lblGreeting)
        self.lblAvatar = QtWidgets.QLabel(parent=self.widget_2)
        self.lblAvatar.setMinimumSize(QtCore.QSize(40, 40))
        self.lblAvatar.setMaximumSize(QtCore.QSize(40, 40))
        self.lblAvatar.setStyleSheet("QLabel {\n"
"    border-radius: 20px; /* Bắt buộc phải bằng đúng 1/2 kích thước Width/Height bạn vừa set ở Lỗi 1 */\n"
"    border-image: url(\"D:/Python/Supermarket_Manager/assets/images/avata.jpg\") 0 0 0 0 stretch stretch;\n"
"    background-color: transparent;\n"
"}")
        self.lblAvatar.setText("")
        self.lblAvatar.setScaledContents(False)
        self.lblAvatar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAvatar.setObjectName("lblAvatar")
        self.horizontalLayout_2.addWidget(self.lblAvatar)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4.addWidget(self.widget_3)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1653, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "RetaiPro ERP"))
        self.label_3.setText(_translate("MainWindow", "Enterprse Sutie"))
        self.btn_dashboard.setText(_translate("MainWindow", "Dashboard"))
        self.btn_products.setText(_translate("MainWindow", "Products"))
        self.btn_suppliers.setText(_translate("MainWindow", "Suppliers"))
        self.btn_importing.setText(_translate("MainWindow", "Importing"))
        self.btn_customers.setText(_translate("MainWindow", "Customers"))
        self.btn_pos.setText(_translate("MainWindow", "POS"))
        self.btn_analytics.setText(_translate("MainWindow", "Analytics"))
        self.btn_settings.setText(_translate("MainWindow", "Sytem Settings"))
        self.btn_help.setText(_translate("MainWindow", "Help Center"))
        self.btn_logout.setText(_translate("MainWindow", "Logout"))
        self.lblDateTime.setText(_translate("MainWindow", "Ngày giờ hiện tại"))
        self.lblGreeting.setText(_translate("MainWindow", "Xin chào !..."))
