# Form implementation generated from reading ui file 'src/gui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1255, 758)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar_frame = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar_frame.sizePolicy().hasHeightForWidth())
        self.sidebar_frame.setSizePolicy(sizePolicy)
        self.sidebar_frame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.sidebar_frame.setStyleSheet("/* 1. Nền sidebar */\n"
"#sidebar_frame {\n"
"    background-color: #334155;\n"
"}\n"
"\n"
"/* 2. Trạng thái thường của nút menu.\n"
"      border-left trong suốt nhưng VẪN rộng 4px để giữ chỗ sẵn cho thanh dọc,\n"
"      nhờ vậy chữ không bị nhảy sang phải khi hover hay khi được chọn.\n"
"      padding-left giảm 30px -> 26px để bù đúng 4px border (4 + 26 = 30),\n"
"      giữ nguyên vị trí chữ so với giao diện cũ. */\n"
"#sidebar_frame QPushButton {\n"
"    background-color: transparent;\n"
"    color: #cbd5e1;\n"
"    text-align: left;\n"
"    padding: 10px 10px 10px 26px;\n"
"    border: none;\n"
"    border-left: 4px solid transparent;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* 3. Hover (rê chuột vào nút chưa chọn): nền sáng nhẹ, chữ trắng,\n"
"      thanh dọc màu XÁM mang nghĩa \"xem trước\" */\n"
"#sidebar_frame QPushButton:hover {\n"
"    background-color: #475569;\n"
"    color: #ffffff;\n"
"    border-left: 4px solid #94a3b8;\n"
"}\n"
"\n"
"/* 4. Active (nút của trang đang mở): nền sáng nhẹ, chữ trắng đậm,\n"
"      thanh dọc màu XANH DƯƠNG nổi bật */\n"
"#sidebar_frame QPushButton:checked {\n"
"    background-color: #475569;\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    border-left: 4px solid #3b82f6;\n"
"}\n"
"\n"
"/* 5. Rê chuột vào chính nút đang active thì VẪN giữ thanh xanh dương.\n"
"      Rule này bắt buộc phải đặt SAU rule :hover, vì khi độ đặc hiệu ngang\n"
"      nhau thì Qt ưu tiên rule đứng sau - đó là cách :checked thắng :hover. */\n"
"#sidebar_frame QPushButton:checked:hover {\n"
"    background-color: #475569;\n"
"    color: #ffffff;\n"
"    border-left: 4px solid #3b82f6;\n"
"}\n"
"\n"
"/* 6. Đổi màu chữ Logo và Tiêu đề thành trắng cho nổi bật */\n"
"#sidebar_frame QLabel {\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* 7. Tiêu đề nhóm menu (MAIN / INVENTORY / SYSTEM).\n"
"      3 label này là con của sidebar_frame nên dính luôn rule số 6 ở trên và\n"
"      bị tô trắng đậm. Muốn đè được rule đó thì selector phải ĐẶC HIỆU HƠN,\n"
"      và ở đây phải viết đủ cả \"#sidebar_frame QLabel#ten_label\":\n"
"        - \"#sidebar_frame QLabel\"        = 1 id + 1 type\n"
"        - \"#lbl_section_main\"            = 1 id + 0 type  -> THUA, không đủ\n"
"        - \"#sidebar_frame QLabel#...\"    = 2 id + 1 type  -> THẮNG\n"
"      padding-left 30px để chữ tiêu đề thẳng hàng với chữ trên nút\n"
"      (nút = border-left 4px + padding-left 26px = 30px).\n"
"      padding-top 12px tạo khoảng thở ngăn cách giữa các nhóm. */\n"
"#sidebar_frame QLabel#lbl_section_main,\n"
"#sidebar_frame QLabel#lbl_section_inventory,\n"
"#sidebar_frame QLabel#lbl_section_system {\n"
"    background-color: transparent;\n"
"    color: #64748b;\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    padding: 12px 10px 4px 30px;\n"
"}\n"
"\n"
"/* 8. Đường kẻ ngang mảnh ngăn giữa phần header (logo + tên app) và phần menu.\n"
"      Đây là QFrame phẳng (NoFrame) chứ KHÔNG dùng frameShape = HLine, vì HLine\n"
"      vẽ đường bằng màu mid/dark/light lấy từ palette chứ không lấy từ QSS, nên\n"
"      trên nền tối sẽ ra vạch nổi 3D sai màu và rất khó ép màu.\n"
"      Mẹo ở đây là dùng box model của QSS: background-color chỉ tô phần NẰM\n"
"      TRONG lề, nên widget cao 11px với lề trên 8px và lề dưới 2px sẽ để lại\n"
"      đúng 1px được tô màu (11 = 8 + 1 + 2), thụt vào 16px mỗi bên.\n"
"      Lề dưới cố ý nhỏ hơn lề trên vì nhãn nhóm \"MAIN\" ngay bên dưới đã tự có\n"
"      sẵn padding-top 12px rồi; để 8px cả hai phía sẽ làm khoảng dưới rộng gấp\n"
"      đôi khoảng trên.\n"
"      Selector viết đủ \"#sidebar_frame QFrame#line_header\" (2 id + 1 type) để\n"
"      chắc chắn thắng mọi rule có sẵn, giống cách đã làm ở rule số 7. */\n"
"#sidebar_frame QFrame#line_header {\n"
"    background-color: #475569;\n"
"    border: none;\n"
"    margin: 8px 16px 2px 16px;\n"
"}")
        self.sidebar_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sidebar_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sidebar_frame.setObjectName("sidebar_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sidebar_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.sidebar_frame)
        self.frame.setMinimumSize(QtCore.QSize(0, 90))
        self.frame.setStyleSheet("#frame {\n"
"    background-color: #334155;\n"
"    border: none; \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setMinimumSize(QtCore.QSize(75, 75))
        self.label_4.setMaximumSize(QtCore.QSize(75, 75))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("src/gui\\../../../../Downloads/logo1.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.verticalLayout.setContentsMargins(-1, 14, -1, 14)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_2.setMaximumSize(QtCore.QSize(140, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #AAB4C3;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.frame)
        self.line_header = QtWidgets.QFrame(parent=self.sidebar_frame)
        self.line_header.setMinimumSize(QtCore.QSize(0, 11))
        self.line_header.setMaximumSize(QtCore.QSize(16777215, 11))
        self.line_header.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.line_header.setObjectName("line_header")
        self.verticalLayout_2.addWidget(self.line_header)
        self.lbl_section_main = QtWidgets.QLabel(parent=self.sidebar_frame)
        self.lbl_section_main.setObjectName("lbl_section_main")
        self.verticalLayout_2.addWidget(self.lbl_section_main)
        self.btn_dashboard = QtWidgets.QPushButton(parent=self.sidebar_frame)
        self.btn_dashboard.setObjectName("btn_dashboard")
        self.verticalLayout_2.addWidget(self.btn_dashboard)
        self.btn_pos = QtWidgets.QPushButton(parent=self.sidebar_frame)
        self.btn_pos.setObjectName("btn_pos")
        self.verticalLayout_2.addWidget(self.btn_pos)
        self.btn_products = QtWidgets.QPushButton(parent=self.sidebar_frame)
        self.btn_products.setObjectName("btn_products")
        self.verticalLayout_2.addWidget(self.btn_products)
        self.btn_customers = QtWidgets.QPushButton(parent=self.sidebar_frame)
        self.btn_customers.setObjectName("btn_customers")
        self.verticalLayout_2.addWidget(self.btn_customers)
        self.lbl_section_inventory = QtWidgets.QLabel(parent=self.sidebar_frame)
        self.lbl_section_inventory.setObjectName("lbl_section_inventory")
        self.verticalLayout_2.addWidget(self.lbl_section_inventory)
        self.btn_suppliers = QtWidgets.QPushButton(parent=self.sidebar_frame)
        self.btn_suppliers.setObjectName("btn_suppliers")
        self.verticalLayout_2.addWidget(self.btn_suppliers)
        self.btn_importing = QtWidgets.QPushButton(parent=self.sidebar_frame)
        self.btn_importing.setObjectName("btn_importing")
        self.verticalLayout_2.addWidget(self.btn_importing)
        self.lbl_section_system = QtWidgets.QLabel(parent=self.sidebar_frame)
        self.lbl_section_system.setObjectName("lbl_section_system")
        self.verticalLayout_2.addWidget(self.lbl_section_system)
        self.btn_analytics = QtWidgets.QPushButton(parent=self.sidebar_frame)
        self.btn_analytics.setObjectName("btn_analytics")
        self.verticalLayout_2.addWidget(self.btn_analytics)
        self.btn_settings = QtWidgets.QPushButton(parent=self.sidebar_frame)
        self.btn_settings.setObjectName("btn_settings")
        self.verticalLayout_2.addWidget(self.btn_settings)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.frame_3 = QtWidgets.QFrame(parent=self.sidebar_frame)
        self.frame_3.setStyleSheet("#frame_3 {\n"
"    background-color: #334155;\n"
"    border: none; \n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_help = QtWidgets.QPushButton(parent=self.frame_3)
        self.btn_help.setObjectName("btn_help")
        self.verticalLayout_3.addWidget(self.btn_help)
        self.btn_logout = QtWidgets.QPushButton(parent=self.frame_3)
        self.btn_logout.setObjectName("btn_logout")
        self.verticalLayout_3.addWidget(self.btn_logout)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.sidebar_frame)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_2.setStyleSheet("#widget_2 {\n"
"    background-color: #ffffff; \n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblDateTime = QtWidgets.QLabel(parent=self.widget_2)
        self.lblDateTime.setStyleSheet("#lblDateTime {\n"
"    color: #1e3a8a;\n"
"    font-size: 12px;\n"
"    font-weight: 500;\n"
"}")
        self.lblDateTime.setObjectName("lblDateTime")
        self.horizontalLayout_2.addWidget(self.lblDateTime)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lblGreeting = QtWidgets.QLabel(parent=self.widget_2)
        self.lblGreeting.setStyleSheet("#lblGreeting {\n"
"    color: #0f172a;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"}")
        self.lblGreeting.setObjectName("lblGreeting")
        self.horizontalLayout_2.addWidget(self.lblGreeting)
        self.lblAvatar = QtWidgets.QLabel(parent=self.widget_2)
        self.lblAvatar.setMinimumSize(QtCore.QSize(30, 30))
        self.lblAvatar.setMaximumSize(QtCore.QSize(40, 40))
        self.lblAvatar.setStyleSheet("QLabel {\n"
"    border-radius: 20px; /* Bắt buộc phải bằng đúng 1/2 kích thước Width/Height bạn vừa set ở Lỗi 1 */\n"
"    border-image: url(:/images/avata.jpg) 0 0 0 0 stretch stretch;\n"
"    background-color: transparent;\n"
"}")
        self.lblAvatar.setText("")
        self.lblAvatar.setScaledContents(False)
        self.lblAvatar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAvatar.setObjectName("lblAvatar")
        self.horizontalLayout_2.addWidget(self.lblAvatar)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4.addWidget(self.widget_3)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1255, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RetaiPro ERP / Trang chủ"))
        self.label_2.setText(_translate("MainWindow", "RetailPro ERP"))
        self.label_3.setText(_translate("MainWindow", "Enterprise Suite"))
        self.lbl_section_main.setText(_translate("MainWindow", "MAIN"))
        self.btn_dashboard.setText(_translate("MainWindow", "Dashboard"))
        self.btn_pos.setText(_translate("MainWindow", "POS"))
        self.btn_products.setText(_translate("MainWindow", "Products"))
        self.btn_customers.setText(_translate("MainWindow", "Customers"))
        self.lbl_section_inventory.setText(_translate("MainWindow", "INVENTORY"))
        self.btn_suppliers.setText(_translate("MainWindow", "Suppliers"))
        self.btn_importing.setText(_translate("MainWindow", "Importing"))
        self.lbl_section_system.setText(_translate("MainWindow", "SYSTEM"))
        self.btn_analytics.setText(_translate("MainWindow", "Analytics"))
        self.btn_settings.setText(_translate("MainWindow", "Sytem Settings"))
        self.btn_help.setText(_translate("MainWindow", "Help Center"))
        self.btn_logout.setText(_translate("MainWindow", "Logout"))
        self.lblDateTime.setText(_translate("MainWindow", "Ngày giờ hiện tại"))
        self.lblGreeting.setText(_translate("MainWindow", "Xin chào !..."))
