# Form implementation generated from reading ui file 'src/gui/new_password.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 680)
        MainWindow.setStyleSheet("#centralwidget {\n"
"    background-color: #f3f4f6;\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.newpass_card = QtWidgets.QFrame(parent=self.centralwidget)
        self.newpass_card.setMinimumSize(QtCore.QSize(420, 480))
        self.newpass_card.setMaximumSize(QtCore.QSize(420, 480))
        self.newpass_card.setStyleSheet("/* ===== Toàn bộ màu sắc của màn hình này nằm ở đây =====\n"
"   Sửa trực tiếp trong Qt Designer: chọn khung newpass_card rồi mở styleSheet.\n"
"   Bảng màu lấy đúng theo form Đăng nhập (login.ui). */\n"
"\n"
"#newpass_card {\n"
"    background-color: #ffffff;\n"
"    border-radius: 12px;\n"
"    border: 1px solid #e5e7eb;\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Tên hệ thống */\n"
"#lblTitle {\n"
"    color: #0c2b82;\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Dòng mô tả dưới tên hệ thống */\n"
"#lblSubtitle {\n"
"    color: #6b7280;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* Đường kẻ ngăn cách */\n"
"#dividerLine {\n"
"    background-color: #e5e7eb;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Nhãn đứng trên ô nhập */\n"
"#lblField1, #lblField2 {\n"
"    color: #374151;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"/* Dòng nhắc luật mật khẩu */\n"
"#lblHint {\n"
"    color: #9ca3af;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#lblCopyright {\n"
"    color: #9ca3af;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #d1d5db;\n"
"    border-radius: 6px;\n"
"    padding: 0px 12px;\n"
"    background-color: #ffffff;\n"
"    color: #111827;\n"
"    font-size: 13px;\n"
"    selection-background-color: #0c2b82;\n"
"    selection-color: #ffffff;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0c2b82;\n"
"}\n"
"\n"
"/* Nút con mắt ẩn/hiện mật khẩu nằm bên trong ô mật khẩu */\n"
"QToolButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    padding: 0px;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"/* Nút chính */\n"
"#pushButton_accept {\n"
"    background-color: #002b9a;\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"#pushButton_accept:hover {\n"
"    background-color: #00227b;\n"
"}\n"
"\n"
"#pushButton_accept:pressed {\n"
"    background-color: #001857;\n"
"}\n"
"\n"
"#pushButton_accept:disabled {\n"
"    background-color: #9ca3af;\n"
"}\n"
"\n"
"/* Nút dạng liên kết */\n"
"#pushButton_2 {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #0c2b82;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"#pushButton_2:hover {\n"
"    color: #081d59;\n"
"    text-decoration: underline;\n"
"}")
        self.newpass_card.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.newpass_card.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.newpass_card.setObjectName("newpass_card")
        self.lblLogo = QtWidgets.QLabel(parent=self.newpass_card)
        self.lblLogo.setGeometry(QtCore.QRect(140, 10, 140, 100))
        self.lblLogo.setMinimumSize(QtCore.QSize(140, 100))
        self.lblLogo.setMaximumSize(QtCore.QSize(112, 80))
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap("src/gui\\../../assets/images/logo.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.lblTitle = QtWidgets.QLabel(parent=self.newpass_card)
        self.lblTitle.setGeometry(QtCore.QRect(10, 101, 401, 30))
        self.lblTitle.setMinimumSize(QtCore.QSize(0, 30))
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.lblSubtitle = QtWidgets.QLabel(parent=self.newpass_card)
        self.lblSubtitle.setGeometry(QtCore.QRect(2, 131, 411, 21))
        self.lblSubtitle.setMinimumSize(QtCore.QSize(0, 21))
        self.lblSubtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.dividerLine = QtWidgets.QFrame(parent=self.newpass_card)
        self.dividerLine.setGeometry(QtCore.QRect(40, 167, 341, 1))
        self.dividerLine.setMinimumSize(QtCore.QSize(0, 1))
        self.dividerLine.setMaximumSize(QtCore.QSize(16777215, 1))
        self.dividerLine.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.dividerLine.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.dividerLine.setObjectName("dividerLine")
        self.lblField1 = QtWidgets.QLabel(parent=self.newpass_card)
        self.lblField1.setGeometry(QtCore.QRect(40, 179, 86, 31))
        self.lblField1.setMinimumSize(QtCore.QSize(0, 24))
        self.lblField1.setObjectName("lblField1")
        self.lineEdit_newpassword = QtWidgets.QLineEdit(parent=self.newpass_card)
        self.lineEdit_newpassword.setGeometry(QtCore.QRect(40, 210, 341, 42))
        self.lineEdit_newpassword.setMinimumSize(QtCore.QSize(0, 42))
        self.lineEdit_newpassword.setMaximumSize(QtCore.QSize(16777215, 42))
        self.lineEdit_newpassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_newpassword.setObjectName("lineEdit_newpassword")
        self.lblField2 = QtWidgets.QLabel(parent=self.newpass_card)
        self.lblField2.setGeometry(QtCore.QRect(40, 260, 138, 31))
        self.lblField2.setMinimumSize(QtCore.QSize(0, 24))
        self.lblField2.setObjectName("lblField2")
        self.lineEdit_againpassword = QtWidgets.QLineEdit(parent=self.newpass_card)
        self.lineEdit_againpassword.setGeometry(QtCore.QRect(40, 291, 341, 42))
        self.lineEdit_againpassword.setMinimumSize(QtCore.QSize(0, 42))
        self.lineEdit_againpassword.setMaximumSize(QtCore.QSize(16777215, 42))
        self.lineEdit_againpassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_againpassword.setObjectName("lineEdit_againpassword")
        self.pushButton_accept = QtWidgets.QPushButton(parent=self.newpass_card)
        self.pushButton_accept.setGeometry(QtCore.QRect(40, 360, 341, 61))
        self.pushButton_accept.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_accept.setMaximumSize(QtCore.QSize(16777215, 61))
        self.pushButton_accept.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.newpass_card)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 420, 51, 61))
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(parent=self.newpass_card)
        self.label.setGeometry(QtCore.QRect(130, 420, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #6b7280;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.newpass_card, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RetailPro ERP / Đặt mật khẩu mới"))
        self.lblTitle.setText(_translate("MainWindow", "RetailPro ERP"))
        self.lblSubtitle.setText(_translate("MainWindow", "Đặt mật khẩu mới cho tài khoản của bạn"))
        self.lblField1.setText(_translate("MainWindow", "Mật khẩu mới:"))
        self.lineEdit_newpassword.setPlaceholderText(_translate("MainWindow", "Tối thiểu 8 ký tự, gồm cả chữ và số"))
        self.lblField2.setText(_translate("MainWindow", "Nhập lại mật khẩu mới:"))
        self.lineEdit_againpassword.setPlaceholderText(_translate("MainWindow", "••••••••"))
        self.pushButton_accept.setText(_translate("MainWindow", "Xác nhận"))
        self.pushButton_2.setText(_translate("MainWindow", "tại đây"))
        self.label.setText(_translate("MainWindow", "Quay lại đăng nhập"))
