# Form implementation generated from reading ui file 'user_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UserDialog(object):
    def setupUi(self, UserDialog):
        UserDialog.setObjectName("UserDialog")
        UserDialog.resize(400, 550)
        self.verticalLayout = QtWidgets.QVBoxLayout(UserDialog)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.lblUsername = QtWidgets.QLabel(parent=UserDialog)
        self.lblUsername.setObjectName("lblUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblUsername)
        self.txtUsername = QtWidgets.QLineEdit(parent=UserDialog)
        self.txtUsername.setObjectName("txtUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtUsername)
        self.lblFullName = QtWidgets.QLabel(parent=UserDialog)
        self.lblFullName.setObjectName("lblFullName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFullName)
        self.txtFullName = QtWidgets.QLineEdit(parent=UserDialog)
        self.txtFullName.setObjectName("txtFullName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtFullName)
        self.lblEmail = QtWidgets.QLabel(parent=UserDialog)
        self.lblEmail.setObjectName("lblEmail")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblEmail)
        self.txtEmail = QtWidgets.QLineEdit(parent=UserDialog)
        self.txtEmail.setObjectName("txtEmail")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtEmail)
        self.lblPassword = QtWidgets.QLabel(parent=UserDialog)
        self.lblPassword.setObjectName("lblPassword")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblPassword)
        self.txtPassword = QtWidgets.QLineEdit(parent=UserDialog)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtPassword)
        self.lblRole = QtWidgets.QLabel(parent=UserDialog)
        self.lblRole.setObjectName("lblRole")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblRole)
        self.cboRole = QtWidgets.QComboBox(parent=UserDialog)
        self.cboRole.setObjectName("cboRole")
        self.cboRole.addItem("")
        self.cboRole.addItem("")
        self.cboRole.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cboRole)
        self.lblStatus = QtWidgets.QLabel(parent=UserDialog)
        self.lblStatus.setObjectName("lblStatus")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblStatus)
        self.chkStatus = QtWidgets.QCheckBox(parent=UserDialog)
        self.chkStatus.setChecked(True)
        self.chkStatus.setObjectName("chkStatus")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.chkStatus)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCancel = QtWidgets.QPushButton(parent=UserDialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.btnSave = QtWidgets.QPushButton(parent=UserDialog)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(UserDialog)
        self.btnCancel.clicked.connect(UserDialog.reject) # type: ignore
        self.btnSave.clicked.connect(UserDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UserDialog)

    def retranslateUi(self, UserDialog):
        _translate = QtCore.QCoreApplication.translate
        UserDialog.setWindowTitle(_translate("UserDialog", "Thêm tài khoản"))
        UserDialog.setStyleSheet(_translate("UserDialog", "/* QSS gốc từ RetailPro ERP */\n"
"QDialog {\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-weight: bold;\n"
"    color: #334155;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit, QComboBox {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 6px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QLineEdit:focus, QComboBox:focus {\n"
"    border: 1px solid #3b82f6;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #f1f5f9;\n"
"    color: #64748b;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font-weight: bold;\n"
"    border-radius: 6px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton#btnSave {\n"
"    background-color: #3b82f6;\n"
"    color: white;\n"
"}\n"
"QPushButton#btnSave:hover { background-color: #2563eb; }\n"
"\n"
"QPushButton#btnCancel {\n"
"    background-color: #e2e8f0;\n"
"    color: #475569;\n"
"}\n"
"QPushButton#btnCancel:hover { background-color: #cbd5e1; }\n"
""))
        self.lblUsername.setText(_translate("UserDialog", "Tên đăng nhập:"))
        self.txtUsername.setPlaceholderText(_translate("UserDialog", "Nhập tên đăng nhập..."))
        self.lblFullName.setText(_translate("UserDialog", "Họ và tên:"))
        self.txtFullName.setPlaceholderText(_translate("UserDialog", "Nhập họ và tên..."))
        self.lblEmail.setText(_translate("UserDialog", "Email:"))
        self.txtEmail.setPlaceholderText(_translate("UserDialog", "Nhập email..."))
        self.lblPassword.setText(_translate("UserDialog", "Mật khẩu:"))
        self.txtPassword.setPlaceholderText(_translate("UserDialog", "Nhập mật khẩu..."))
        self.lblRole.setText(_translate("UserDialog", "Chức vụ:"))
        self.cboRole.setItemText(0, _translate("UserDialog", "Admin"))
        self.cboRole.setItemText(1, _translate("UserDialog", "Manager"))
        self.cboRole.setItemText(2, _translate("UserDialog", "Cashier"))
        self.lblStatus.setText(_translate("UserDialog", "Trạng thái:"))
        self.chkStatus.setStyleSheet(_translate("UserDialog", "QCheckBox { color: #10b981; font-weight: bold; }"))
        self.chkStatus.setText(_translate("UserDialog", "Hoạt động"))
        self.btnCancel.setText(_translate("UserDialog", "HỦY"))
        self.btnSave.setText(_translate("UserDialog", "LƯU"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserDialog = QtWidgets.QDialog()
    ui = Ui_UserDialog()
    ui.setupUi(UserDialog)
    UserDialog.show()
    sys.exit(app.exec())
