# Form implementation generated from reading ui file 'src/gui/verification_code.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 680)
        MainWindow.setStyleSheet("#centralwidget {\n"
"    background-color: #f3f4f6;\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.code_card = QtWidgets.QFrame(parent=self.centralwidget)
        self.code_card.setMinimumSize(QtCore.QSize(420, 445))
        self.code_card.setMaximumSize(QtCore.QSize(420, 445))
        self.code_card.setStyleSheet("/* ===== Toàn bộ màu sắc của màn hình này nằm ở đây =====\n"
"   Sửa trực tiếp trong Qt Designer: chọn khung code_card rồi mở styleSheet.\n"
"   Bảng màu lấy đúng theo form Đăng nhập (login.ui). */\n"
"\n"
"#code_card {\n"
"    background-color: #ffffff;\n"
"    border-radius: 12px;\n"
"    border: 1px solid #e5e7eb;\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Tên hệ thống */\n"
"#lblTitle {\n"
"    color: #0c2b82;\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Dòng mô tả dưới tên hệ thống */\n"
"#lblSubtitle {\n"
"    color: #6b7280;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* Đường kẻ ngăn cách */\n"
"#dividerLine {\n"
"    background-color: #e5e7eb;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Nhãn đứng trên ô nhập */\n"
"#lblField {\n"
"    color: #374151;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#lblCopyright {\n"
"    color: #9ca3af;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #d1d5db;\n"
"    border-radius: 6px;\n"
"    padding: 0px 12px;\n"
"    background-color: #ffffff;\n"
"    color: #111827;\n"
"    font-size: 13px;\n"
"    selection-background-color: #0c2b82;\n"
"    selection-color: #ffffff;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0c2b82;\n"
"}\n"
"\n"
"/* Nút chính */\n"
"#pushButton_accept {\n"
"    background-color: #002b9a;\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"#pushButton_accept:hover {\n"
"    background-color: #00227b;\n"
"}\n"
"\n"
"#pushButton_accept:pressed {\n"
"    background-color: #001857;\n"
"}\n"
"\n"
"#pushButton_accept:disabled {\n"
"    background-color: #9ca3af;\n"
"}\n"
"\n"
"/* Nút dạng liên kết */\n"
"#pushButton_resend, #pushButton_2 {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #0c2b82;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"#pushButton_resend:hover, #pushButton_2:hover {\n"
"    color: #081d59;\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"/* Lúc đang trong thời gian chờ gửi lại mã */\n"
"#pushButton_resend:disabled {\n"
"    color: #9ca3af;\n"
"    text-decoration: none;\n"
"}")
        self.code_card.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.code_card.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.code_card.setObjectName("code_card")
        self.lblLogo = QtWidgets.QLabel(parent=self.code_card)
        self.lblLogo.setGeometry(QtCore.QRect(140, 20, 140, 100))
        self.lblLogo.setMinimumSize(QtCore.QSize(140, 100))
        self.lblLogo.setMaximumSize(QtCore.QSize(140, 100))
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap("src/gui\\../../assets/images/logo.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.lblTitle = QtWidgets.QLabel(parent=self.code_card)
        self.lblTitle.setGeometry(QtCore.QRect(10, 121, 401, 30))
        self.lblTitle.setMinimumSize(QtCore.QSize(0, 30))
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.lblSubtitle = QtWidgets.QLabel(parent=self.code_card)
        self.lblSubtitle.setGeometry(QtCore.QRect(10, 151, 401, 21))
        self.lblSubtitle.setMinimumSize(QtCore.QSize(0, 21))
        self.lblSubtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.dividerLine = QtWidgets.QFrame(parent=self.code_card)
        self.dividerLine.setGeometry(QtCore.QRect(40, 195, 341, 1))
        self.dividerLine.setMinimumSize(QtCore.QSize(0, 1))
        self.dividerLine.setMaximumSize(QtCore.QSize(16777215, 1))
        self.dividerLine.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.dividerLine.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.dividerLine.setObjectName("dividerLine")
        self.lblField = QtWidgets.QLabel(parent=self.code_card)
        self.lblField.setGeometry(QtCore.QRect(40, 208, 75, 31))
        self.lblField.setMinimumSize(QtCore.QSize(0, 24))
        self.lblField.setObjectName("lblField")
        self.lineEdit_code = QtWidgets.QLineEdit(parent=self.code_card)
        self.lineEdit_code.setGeometry(QtCore.QRect(40, 239, 341, 42))
        self.lineEdit_code.setMinimumSize(QtCore.QSize(0, 42))
        self.lineEdit_code.setMaximumSize(QtCore.QSize(16777215, 42))
        self.lineEdit_code.setMaxLength(6)
        self.lineEdit_code.setObjectName("lineEdit_code")
        self.pushButton_accept = QtWidgets.QPushButton(parent=self.code_card)
        self.pushButton_accept.setGeometry(QtCore.QRect(40, 330, 341, 61))
        self.pushButton_accept.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_accept.setMaximumSize(QtCore.QSize(16777215, 61))
        self.pushButton_accept.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.code_card)
        self.pushButton_2.setGeometry(QtCore.QRect(232, 391, 61, 51))
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.layoutWidget = QtWidgets.QWidget(parent=self.code_card)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 281, 341, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_resend = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_resend.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_resend.setSpacing(0)
        self.horizontalLayout_resend.setObjectName("horizontalLayout_resend")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_resend.addItem(spacerItem)
        self.pushButton_resend = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_resend.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButton_resend.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_resend.setObjectName("pushButton_resend")
        self.horizontalLayout_resend.addWidget(self.pushButton_resend)
        self.label = QtWidgets.QLabel(parent=self.code_card)
        self.label.setGeometry(QtCore.QRect(120, 390, 123, 51))
        self.label.setMinimumSize(QtCore.QSize(123, 0))
        self.label.setMaximumSize(QtCore.QSize(123, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #6b7280;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.code_card, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RetailPro ERP / Xác thực mã"))
        self.lblTitle.setText(_translate("MainWindow", "RetailPro ERP"))
        self.lblSubtitle.setText(_translate("MainWindow", "Nhập mã xác thực đã gửi tới email của bạn"))
        self.lblField.setText(_translate("MainWindow", "Mã xác thực:"))
        self.lineEdit_code.setPlaceholderText(_translate("MainWindow", "Nhập 6 chữ số"))
        self.pushButton_accept.setText(_translate("MainWindow", "Xác nhận"))
        self.pushButton_2.setText(_translate("MainWindow", "tại đây"))
        self.pushButton_resend.setText(_translate("MainWindow", "Gửi lại mã"))
        self.label.setText(_translate("MainWindow", "Quay lại đăng nhập"))
