# Form implementation generated from reading ui file 'src/gui/tabs/dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1536, 924)
        Form.setStyleSheet("/* ===== QSS tập trung của Dashboard =====\n"
"   Trước đây nằm rải rác trong DashboardController.py.\n"
"   Gom về đây để chỉnh giao diện trực tiếp trong Qt Designer.\n"
"   QSS đặt ở widget gốc sẽ lan xuống mọi widget con, kể cả\n"
"   widget được tạo lúc chạy (bảng, huy hiệu icon, nhãn ô thao tác). */\n"
"\n"
"/* Nút \"Tải lại dữ liệu\" trên thanh tiêu đề.\n"
"   Dùng chung bảng màu với nút chính của tab POS (#btnCheckout, #btnCardAdd)\n"
"   để hai tab nhìn đồng bộ. */\n"
"QPushButton#pushButton {\n"
"    background-color: #1d4ed8;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 0px 14px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton#pushButton:hover {\n"
"    background-color: #1e3a8a;\n"
"}\n"
"QPushButton#pushButton:pressed {\n"
"    background-color: #1e40af;\n"
"}\n"
"/* Trạng thái \"Đang tải...\" khi controller tạm khoá nút */\n"
"QPushButton#pushButton:disabled {\n"
"    background-color: #cbd5e1;\n"
"    color: #f8fafc;\n"
"}\n"
"\n"
"/* Tiêu đề khối \"Giao dịch gần đây\" */\n"
"QLabel#lblTableTitle {\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    color: #1e293b;\n"
"}\n"
"\n"
"/* Bảng giao dịch gần đây */\n"
"QTableWidget#tblRecentTransactions {\n"
"    border: none;\n"
"    gridline-color: #f1f5f9;\n"
"    background-color: white;\n"
"}\n"
"QTableWidget#tblRecentTransactions::item {\n"
"    padding: 10px;\n"
"    border-bottom: 1px solid #f8fafc;\n"
"}\n"
"QTableWidget#tblRecentTransactions QHeaderView::section {\n"
"    background-color: #f8fafc;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    color: #475569;\n"
"}\n"
"\n"
"/* Chữ chú thích dưới 4 ô thao tác nhanh */\n"
"QLabel#lblQuickActionCaption {\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    color: #475569;\n"
"}\n"
"\n"
"/* Huy hiệu nền bo góc phía sau icon của 4 thẻ thống kê */\n"
"QLabel#badgeRevenue  { background-color: #dbeafe; border-radius: 8px; }\n"
"QLabel#badgeInvoice  { background-color: #ede9fe; border-radius: 8px; }\n"
"QLabel#badgeStock    { background-color: #fef3c7; border-radius: 8px; }\n"
"QLabel#badgeCustomer { background-color: #d1fae5; border-radius: 8px; }\n"
"\n"
"/* Nhãn đổi màu theo dữ liệu.\n"
"   Controller chỉ gán thuộc tính động trangThai, màu do QSS dưới đây quyết định. */\n"
"QLabel[trangThai=\"tang\"]    { color: #10b981; font-weight: bold; }\n"
"QLabel[trangThai=\"giam\"]    { color: #ef4444; font-weight: bold; }\n"
"QLabel[trangThai=\"giu\"]     { color: #64748b; font-weight: bold; }\n"
"QLabel[trangThai=\"canhBao\"] { color: #eab308; font-weight: bold; }\n"
"QLabel[trangThai=\"anToan\"]  { color: #10b981; }")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 64))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_10 = QtWidgets.QFrame(parent=self.frame)
        self.frame_10.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setStyleSheet("#frame_10 {\n"
"        background-color: transparent;\n"
"        color: black;\n"
"        border: none;\n"
"        outline: none;\n"
"        padding: 0px;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.formLayout = QtWidgets.QFormLayout(self.frame_10)
        self.formLayout.setContentsMargins(0, 0, 0, 10)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.frame_10)
        self.label.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_2.setMinimumSize(QtCore.QSize(11, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.label_2.raise_()
        self.label.raise_()
        self.horizontalLayout_2.addWidget(self.frame_10)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(140, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(140, 40))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("#frame_6 {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_2.setContentsMargins(14, 12, 14, 14)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_9.setStyleSheet("QFrame#frame_9 {\n"
"    background-color: #f1f5f9;\n"
"    border-radius: 10px;\n"
"    border: 1px solid #e2e8f0;\n"
"}\n"
"\n"
"QFrame#frame_9:hover {\n"
"    background-color: #e2e8f0;\n"
"    border: 1px solid #cbd5e1;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_2.addWidget(self.frame_9, 2, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_11.setStyleSheet("QFrame#frame_11 {\n"
"    background-color: #f1f5f9;\n"
"    border-radius: 10px;\n"
"    border: 1px solid #e2e8f0;\n"
"}\n"
"\n"
"QFrame#frame_11:hover {\n"
"    background-color: #e2e8f0;\n"
"    border: 1px solid #cbd5e1;\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_2.addWidget(self.frame_11, 1, 1, 1, 1)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_7.setStyleSheet("QFrame#frame_7 {\n"
"    background-color: #f1f5f9;\n"
"    border-radius: 10px;\n"
"    border: 1px solid #e2e8f0;\n"
"}\n"
"\n"
"QFrame#frame_7:hover {\n"
"    background-color: #e2e8f0;\n"
"    border: 1px solid #cbd5e1;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_2.addWidget(self.frame_7, 1, 0, 1, 1)
        self.frame_12 = QtWidgets.QFrame(parent=self.frame_6)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_12)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.gridLayout_2.addWidget(self.frame_12, 0, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_8.setStyleSheet("QFrame#frame_8 {\n"
"    background-color: #f1f5f9;\n"
"    border-radius: 10px;\n"
"    border: 1px solid #e2e8f0;\n"
"}\n"
"\n"
"QFrame#frame_8:hover {\n"
"    background-color: #e2e8f0;\n"
"    border: 1px solid #cbd5e1;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_2.addWidget(self.frame_8, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_6, 0, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_17 = QtWidgets.QFrame(parent=self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy)
        self.frame_17.setStyleSheet("#frame_17 {\n"
"        background-color: white;\n"
"        border-radius: 10px;\n"
"        padding: 3px 8px;\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_17)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.label_14 = QtWidgets.QLabel(parent=self.frame_17)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.label_7 = QtWidgets.QLabel(parent=self.frame_17)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.gridLayout_4.addWidget(self.frame_17, 0, 1, 1, 1)
        self.frame_16 = QtWidgets.QFrame(parent=self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setStyleSheet("#frame_16 {\n"
"        background-color:  white;\n"
"        border-radius: 10px;\n"
"        padding: 3px 8px;\n"
"}")
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(parent=self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.label_13 = QtWidgets.QLabel(parent=self.frame_16)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13)
        self.gridLayout_4.addWidget(self.frame_16, 1, 0, 1, 1)
        self.frame_15 = QtWidgets.QFrame(parent=self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setStyleSheet("#frame_15 {\n"
"        background-color: white;\n"
"        border-radius: 10px;\n"
"        padding: 3px 8px;\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(parent=self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.label_15 = QtWidgets.QLabel(parent=self.frame_15)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_7.addWidget(self.label_15)
        self.gridLayout_4.addWidget(self.frame_15, 1, 1, 1, 1)
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setStyleSheet("#frame_14 {\n"
"        background-color: white;\n"
"        border-radius: 10px;\n"
"        padding: 3px 8px;\n"
"}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_12 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.label_5.raise_()
        self.label_12.raise_()
        self.label_4.raise_()
        self.gridLayout_4.addWidget(self.frame_14, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_13)
        self.gridLayout.addWidget(self.frame_5, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_bottom = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_bottom.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_bottom.setSpacing(12)
        self.horizontalLayout_bottom.setObjectName("horizontalLayout_bottom")
        self.frame_chart = QtWidgets.QFrame(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_chart.sizePolicy().hasHeightForWidth())
        self.frame_chart.setSizePolicy(sizePolicy)
        self.frame_chart.setStyleSheet("QFrame#frame_chart { background-color: white; border-radius: 10px; border: 1px solid #dcdcdc; }")
        self.frame_chart.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_chart.setObjectName("frame_chart")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_chart)
        self.verticalLayout_8.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_18 = QtWidgets.QFrame(parent=self.frame_chart)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 32))
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_18.setStyleSheet("#frame_18{\n"
"    padding: 0px;\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_16 = QtWidgets.QLabel(parent=self.frame_18)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.comboBox = QtWidgets.QComboBox(parent=self.frame_18)
        self.comboBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.verticalLayout_8.addWidget(self.frame_18)
        self.chart_container = QtWidgets.QWidget(parent=self.frame_chart)
        self.chart_container.setObjectName("chart_container")
        self.verticalLayout_8.addWidget(self.chart_container)
        self.horizontalLayout_bottom.addWidget(self.frame_chart)
        self.frame_table = QtWidgets.QFrame(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_table.sizePolicy().hasHeightForWidth())
        self.frame_table.setSizePolicy(sizePolicy)
        self.frame_table.setStyleSheet("QFrame#frame_table { background-color: white; border-radius: 10px; border: 1px solid #dcdcdc; }")
        self.frame_table.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_table.setObjectName("frame_table")
        self.horizontalLayout_bottom.addWidget(self.frame_table)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Tổng quan hệ thống"))
        self.label_2.setText(_translate("Form", "Hôm nay, 24, tháng 10, năm 2023"))
        self.pushButton.setText(_translate("Form", "Tải lại dữ liệu"))
        self.label_3.setText(_translate("Form", "Thao tác nhanh"))
        self.label_6.setText(_translate("Form", "Tổng hóa đơn"))
        self.label_14.setText(_translate("Form", "Số hóa đơn"))
        self.label_7.setText(_translate("Form", "tỉ lệ tăng trưởng"))
        self.label_8.setText(_translate("Form", "Sắp hết hàng"))
        self.label_9.setText(_translate("Form", "số hàng sắp hết"))
        self.label_13.setText(_translate("Form", "Cần cập nhật ngay"))
        self.label_10.setText(_translate("Form", "Khách hàng mới"))
        self.label_11.setText(_translate("Form", "Số khách hàng mới"))
        self.label_15.setText(_translate("Form", "tỉ lệ tăng trưởng"))
        self.label_4.setText(_translate("Form", "Doanh thu hôm nay"))
        self.label_5.setText(_translate("Form", "số tiền hôm nay"))
        self.label_12.setText(_translate("Form", "tỉ lệ tăng trưởng"))
        self.label_16.setText(_translate("Form", "Doanh thu tháng này"))
        self.comboBox.setItemText(0, _translate("Form", "Tháng 1"))
        self.comboBox.setItemText(1, _translate("Form", "Tháng 2"))
        self.comboBox.setItemText(2, _translate("Form", "Tháng 3"))
        self.comboBox.setItemText(3, _translate("Form", "Tháng 4"))
        self.comboBox.setItemText(4, _translate("Form", "Tháng 5"))
        self.comboBox.setItemText(5, _translate("Form", "Tháng 6"))
        self.comboBox.setItemText(6, _translate("Form", "Tháng 7"))
        self.comboBox.setItemText(7, _translate("Form", "Tháng 8"))
        self.comboBox.setItemText(8, _translate("Form", "Tháng 9"))
        self.comboBox.setItemText(9, _translate("Form", "Tháng 10"))
        self.comboBox.setItemText(10, _translate("Form", "Tháng 11"))
        self.comboBox.setItemText(11, _translate("Form", "Tháng 12"))
