# Form implementation generated from reading ui file 'src/gui/tabs/pos.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 860)
        Form.setStyleSheet("/* ===== General ===== */\n"
"\n"
"QWidget {\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"\n"
"/* ===== Top bar ===== */\n"
"\n"
"#frame_topbar {\n"
"    background-color: #ffffff;\n"
"    border-bottom: 1px solid #e2e8f0;\n"
"}\n"
"\n"
"#lblScanCaption {\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#lblCashierName {\n"
"    color: #64748b;\n"
"}\n"
"\n"
"\n"
"/* ===== Search and filters ===== */\n"
"\n"
"#frame_filters {\n"
"    background-color: #ffffff;\n"
"    border-bottom: 1px solid #e2e8f0;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #e2e8f0;\n"
"    border-radius: 8px;\n"
"    padding: 4px 12px;\n"
"    font-size: 13px;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #1d4ed8;\n"
"}\n"
"\n"
"\n"
"/* ===== Category chips ===== */\n"
"\n"
"#CategoryChip {\n"
"    background-color: #ffffff;\n"
"    color: #64748b;\n"
"    border: 1px solid #e2e8f0;\n"
"    border-radius: 16px;\n"
"    padding: 4px 16px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#CategoryChip:hover {\n"
"    border: 1px solid #1d4ed8;\n"
"    color: #1d4ed8;\n"
"}\n"
"\n"
"#CategoryChip:checked {\n"
"    background-color: #1e3a8a;\n"
"    color: #ffffff;\n"
"    border: 1px solid #1e3a8a;\n"
"}\n"
"\n"
"\n"
"/* ===== Small buttons ===== */\n"
"\n"
"#btnFilter,\n"
"#btnAddCustomer {\n"
"    background-color: #ffffff;\n"
"    color: #64748b;\n"
"    border: 1px solid #e2e8f0;\n"
"    border-radius: 8px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#btnFilter:hover,\n"
"#btnAddCustomer:hover {\n"
"    background-color: #eff6ff;\n"
"    color: #1d4ed8;\n"
"    border: 1px solid #1d4ed8;\n"
"}\n"
"\n"
"#btnClearCart {\n"
"    background-color: #ffffff;\n"
"    color: #dc2626;\n"
"    border: 1px solid #e2e8f0;\n"
"    border-radius: 8px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#btnClearCart:hover {\n"
"    background-color: #fef2f2;\n"
"    border: 1px solid #dc2626;\n"
"}\n"
"\n"
"\n"
"/* ===== Scroll areas ===== */\n"
"\n"
"QScrollArea {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"/* ===== Vertical scrollbar ===== */\n"
"\n"
"QScrollBar:vertical {\n"
"    background-color: #f8fafc;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #cbd5e1;\n"
"    min-height: 35px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #94a3b8;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed {\n"
"    background-color: #64748b;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"    width: 0px;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: transparent;\n"
"}\n"
"\n"
"\n"
"/* ===== Horizontal scrollbar ===== */\n"
"\n"
"QScrollBar:horizontal {\n"
"    background-color: #f8fafc;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #cbd5e1;\n"
"    min-width: 35px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: #94a3b8;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:pressed {\n"
"    background-color: #64748b;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::left-arrow:horizontal,\n"
"QScrollBar::right-arrow:horizontal {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: transparent;\n"
"}\n"
"\n"
"\n"
"/* ===== Product card ===== */\n"
"\n"
"#ProductCard {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #e2e8f0;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#ProductCard:hover {\n"
"    border: 1px solid #1d4ed8;\n"
"}\n"
"\n"
"#lblCardThumbnail {\n"
"    background-color: #fbfcfd;\n"
"    border: 1px solid #e2e8f0;\n"
"    border-radius: 8px;\n"
"    color: #64748b;\n"
"}\n"
"\n"
"#lblCardName {\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#lblCardBarcode {\n"
"    color: #64748b;\n"
"    font-size: 11px;\n"
"}\n"
"\n"
"#lblCardPrice {\n"
"    color: #1d4ed8;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#btnCardAdd {\n"
"    background-color: #1d4ed8;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#btnCardAdd:hover {\n"
"    background-color: #1e3a8a;\n"
"}\n"
"\n"
"\n"
"/* ===== Shortcuts ===== */\n"
"\n"
"#frame_shortcuts {\n"
"    background-color: #ffffff;\n"
"    border-top: 1px solid #e2e8f0;\n"
"}\n"
"\n"
"\n"
"/* ===== Order panel ===== */\n"
"\n"
"#frame_order {\n"
"    background-color: #ffffff;\n"
"    border-left: 1px solid #e2e8f0;\n"
"}\n"
"\n"
"#frame_order_header {\n"
"    background-color: #ffffff;\n"
"    border-bottom: 1px solid #e2e8f0;\n"
"}\n"
"\n"
"#lblCustomerBadge {\n"
"    background-color: #eff6ff;\n"
"    color: #1d4ed8;\n"
"    border-radius: 12px;\n"
"    padding: 4px 12px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#lblCartEmpty {\n"
"    color: #64748b;\n"
"}\n"
"\n"
"\n"
"/* ===== Cart rows ===== */\n"
"\n"
"#CartRow {\n"
"    background-color: #ffffff;\n"
"    border: none;\n"
"    border-bottom: 1px solid #f1f5f9;\n"
"}\n"
"\n"
"#lblCartItemName,\n"
"#lblCartItemTotal {\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#lblCartItemUnitPrice {\n"
"    color: #64748b;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#lblCartItemQuantity {\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"#btnCartMinus,\n"
"#btnCartPlus {\n"
"    background-color: #ffffff;\n"
"    color: #0f172a;\n"
"    border: 1px solid #e2e8f0;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#btnCartMinus:hover,\n"
"#btnCartPlus:hover {\n"
"    background-color: #eff6ff;\n"
"    border: 1px solid #1d4ed8;\n"
"    color: #1d4ed8;\n"
"}\n"
"\n"
"#btnCartRemove {\n"
"    background-color: #ffffff;\n"
"    color: #94a3b8;\n"
"    border: 1px solid #e2e8f0;\n"
"    border-radius: 6px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#btnCartRemove:hover {\n"
"    background-color: #fef2f2;\n"
"    border: 1px solid #dc2626;\n"
"    color: #dc2626;\n"
"}\n"
"\n"
"\n"
"/* ===== Order summary ===== */\n"
"\n"
"#frame_summary {\n"
"    background-color: #ffffff;\n"
"    border-top: 1px solid #e2e8f0;\n"
"}\n"
"\n"
"#lblSubTotalCaption,\n"
"#lblTaxCaption {\n"
"    color: #64748b;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"#lblSubTotal,\n"
"#lblTax {\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"#lblDiscount {\n"
"    color: #dc2626;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"#btnEditDiscount {\n"
"    background-color: transparent;\n"
"    color: #64748b;\n"
"    border: none;\n"
"    text-align: left;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"#btnEditDiscount:hover {\n"
"    color: #1d4ed8;\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"#line_summary {\n"
"    color: #e2e8f0;\n"
"    background-color: #e2e8f0;\n"
"}\n"
"\n"
"#lblGrandTotal {\n"
"    color: #1d4ed8;\n"
"}\n"
"\n"
"\n"
"/* ===== Payment methods ===== */\n"
"\n"
"#btnPayCash,\n"
"#btnPayCard,\n"
"#btnPayTransfer {\n"
"    background-color: #ffffff;\n"
"    color: #64748b;\n"
"    border: 1px solid #e2e8f0;\n"
"    border-radius: 8px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#btnPayCash:hover,\n"
"#btnPayCard:hover,\n"
"#btnPayTransfer:hover {\n"
"    border: 1px solid #1d4ed8;\n"
"    color: #1d4ed8;\n"
"}\n"
"\n"
"#btnPayCash:checked,\n"
"#btnPayCard:checked,\n"
"#btnPayTransfer:checked {\n"
"    background-color: #eff6ff;\n"
"    border: 1px solid #1d4ed8;\n"
"    color: #1d4ed8;\n"
"}\n"
"\n"
"\n"
"/* ===== Checkout ===== */\n"
"\n"
"#btnCheckout {\n"
"    background-color: #1e3a8a;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#btnCheckout:hover {\n"
"    background-color: #1d4ed8;\n"
"}\n"
"\n"
"#btnCheckout:disabled {\n"
"    background-color: #cbd5e1;\n"
"    color: #f8fafc;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_catalog = QtWidgets.QWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_catalog.sizePolicy().hasHeightForWidth())
        self.widget_catalog.setSizePolicy(sizePolicy)
        self.widget_catalog.setObjectName("widget_catalog")
        self.verticalLayout_catalog = QtWidgets.QVBoxLayout(self.widget_catalog)
        self.verticalLayout_catalog.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_catalog.setSpacing(0)
        self.verticalLayout_catalog.setObjectName("verticalLayout_catalog")
        self.frame_topbar = QtWidgets.QFrame(parent=self.widget_catalog)
        self.frame_topbar.setMinimumSize(QtCore.QSize(0, 64))
        self.frame_topbar.setMaximumSize(QtCore.QSize(16777215, 64))
        self.frame_topbar.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_topbar.setObjectName("frame_topbar")
        self.horizontalLayout_topbar = QtWidgets.QHBoxLayout(self.frame_topbar)
        self.horizontalLayout_topbar.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_topbar.setObjectName("horizontalLayout_topbar")
        self.lblScanCaption = QtWidgets.QLabel(parent=self.frame_topbar)
        self.lblScanCaption.setObjectName("lblScanCaption")
        self.horizontalLayout_topbar.addWidget(self.lblScanCaption)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_topbar.addItem(spacerItem)
        self.lblCashierName = QtWidgets.QLabel(parent=self.frame_topbar)
        self.lblCashierName.setObjectName("lblCashierName")
        self.horizontalLayout_topbar.addWidget(self.lblCashierName)
        self.verticalLayout_catalog.addWidget(self.frame_topbar)
        self.frame_filters = QtWidgets.QFrame(parent=self.widget_catalog)
        self.frame_filters.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_filters.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_filters.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_filters.setObjectName("frame_filters")
        self.verticalLayout_filters = QtWidgets.QVBoxLayout(self.frame_filters)
        self.verticalLayout_filters.setContentsMargins(20, 14, 20, -1)
        self.verticalLayout_filters.setObjectName("verticalLayout_filters")
        self.frame_search_row = QtWidgets.QFrame(parent=self.frame_filters)
        self.frame_search_row.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_search_row.setObjectName("frame_search_row")
        self.horizontalLayout_search_row = QtWidgets.QHBoxLayout(self.frame_search_row)
        self.horizontalLayout_search_row.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_search_row.setObjectName("horizontalLayout_search_row")
        self.txtSearch = QtWidgets.QLineEdit(parent=self.frame_search_row)
        self.txtSearch.setMinimumSize(QtCore.QSize(0, 40))
        self.txtSearch.setObjectName("txtSearch")
        self.horizontalLayout_search_row.addWidget(self.txtSearch)
        self.btnFilter = QtWidgets.QPushButton(parent=self.frame_search_row)
        self.btnFilter.setMinimumSize(QtCore.QSize(46, 40))
        self.btnFilter.setMaximumSize(QtCore.QSize(46, 40))
        self.btnFilter.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnFilter.setObjectName("btnFilter")
        self.horizontalLayout_search_row.addWidget(self.btnFilter)
        self.verticalLayout_filters.addWidget(self.frame_search_row)
        self.frame_categories = QtWidgets.QFrame(parent=self.frame_filters)
        self.frame_categories.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_categories.setObjectName("frame_categories")
        self.horizontalLayout_categories = QtWidgets.QHBoxLayout(self.frame_categories)
        self.horizontalLayout_categories.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_categories.setSpacing(8)
        self.horizontalLayout_categories.setObjectName("horizontalLayout_categories")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_categories.addItem(spacerItem1)
        self.verticalLayout_filters.addWidget(self.frame_categories)
        self.verticalLayout_catalog.addWidget(self.frame_filters)
        self.scrollProducts = QtWidgets.QScrollArea(parent=self.widget_catalog)
        self.scrollProducts.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollProducts.setWidgetResizable(True)
        self.scrollProducts.setObjectName("scrollProducts")
        self.widget_products = QtWidgets.QWidget()
        self.widget_products.setGeometry(QtCore.QRect(0, 0, 860, 630))
        self.widget_products.setObjectName("widget_products")
        self.gridLayout_products = QtWidgets.QGridLayout(self.widget_products)
        self.gridLayout_products.setContentsMargins(20, 10, 20, 20)
        self.gridLayout_products.setSpacing(14)
        self.gridLayout_products.setObjectName("gridLayout_products")
        self.scrollProducts.setWidget(self.widget_products)
        self.verticalLayout_catalog.addWidget(self.scrollProducts)
        self.frame_shortcuts = QtWidgets.QFrame(parent=self.widget_catalog)
        self.frame_shortcuts.setMinimumSize(QtCore.QSize(0, 46))
        self.frame_shortcuts.setMaximumSize(QtCore.QSize(16777215, 46))
        self.frame_shortcuts.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_shortcuts.setObjectName("frame_shortcuts")
        self.horizontalLayout_shortcuts = QtWidgets.QHBoxLayout(self.frame_shortcuts)
        self.horizontalLayout_shortcuts.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_shortcuts.setSpacing(18)
        self.horizontalLayout_shortcuts.setObjectName("horizontalLayout_shortcuts")
        self.lblHintHelp = QtWidgets.QLabel(parent=self.frame_shortcuts)
        self.lblHintHelp.setObjectName("lblHintHelp")
        self.horizontalLayout_shortcuts.addWidget(self.lblHintHelp)
        self.lblHintDiscount = QtWidgets.QLabel(parent=self.frame_shortcuts)
        self.lblHintDiscount.setObjectName("lblHintDiscount")
        self.horizontalLayout_shortcuts.addWidget(self.lblHintDiscount)
        self.lblHintQuantity = QtWidgets.QLabel(parent=self.frame_shortcuts)
        self.lblHintQuantity.setObjectName("lblHintQuantity")
        self.horizontalLayout_shortcuts.addWidget(self.lblHintQuantity)
        self.lblHintPay = QtWidgets.QLabel(parent=self.frame_shortcuts)
        self.lblHintPay.setObjectName("lblHintPay")
        self.horizontalLayout_shortcuts.addWidget(self.lblHintPay)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_shortcuts.addItem(spacerItem2)
        self.verticalLayout_catalog.addWidget(self.frame_shortcuts)
        self.horizontalLayout.addWidget(self.widget_catalog)
        self.frame_order = QtWidgets.QFrame(parent=Form)
        self.frame_order.setMinimumSize(QtCore.QSize(420, 0))
        self.frame_order.setMaximumSize(QtCore.QSize(460, 16777215))
        self.frame_order.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_order.setObjectName("frame_order")
        self.verticalLayout_order = QtWidgets.QVBoxLayout(self.frame_order)
        self.verticalLayout_order.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_order.setSpacing(0)
        self.verticalLayout_order.setObjectName("verticalLayout_order")
        self.frame_order_header = QtWidgets.QFrame(parent=self.frame_order)
        self.frame_order_header.setMinimumSize(QtCore.QSize(0, 110))
        self.frame_order_header.setMaximumSize(QtCore.QSize(16777215, 110))
        self.frame_order_header.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_order_header.setObjectName("frame_order_header")
        self.gridLayout_order_header = QtWidgets.QGridLayout(self.frame_order_header)
        self.gridLayout_order_header.setContentsMargins(20, 18, 20, -1)
        self.gridLayout_order_header.setObjectName("gridLayout_order_header")
        self.lblOrderCode = QtWidgets.QLabel(parent=self.frame_order_header)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.lblOrderCode.setFont(font)
        self.lblOrderCode.setObjectName("lblOrderCode")
        self.gridLayout_order_header.addWidget(self.lblOrderCode, 0, 0, 1, 1)
        self.btnAddCustomer = QtWidgets.QPushButton(parent=self.frame_order_header)
        self.btnAddCustomer.setMinimumSize(QtCore.QSize(99, 36))
        self.btnAddCustomer.setMaximumSize(QtCore.QSize(40, 36))
        self.btnAddCustomer.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnAddCustomer.setStyleSheet("")
        self.btnAddCustomer.setObjectName("btnAddCustomer")
        self.gridLayout_order_header.addWidget(self.btnAddCustomer, 0, 1, 1, 1)
        self.btnClearCart = QtWidgets.QPushButton(parent=self.frame_order_header)
        self.btnClearCart.setMinimumSize(QtCore.QSize(40, 36))
        self.btnClearCart.setMaximumSize(QtCore.QSize(40, 36))
        self.btnClearCart.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnClearCart.setText("")
        self.btnClearCart.setObjectName("btnClearCart")
        self.gridLayout_order_header.addWidget(self.btnClearCart, 0, 2, 1, 1)
        self.lblCustomerBadge = QtWidgets.QLabel(parent=self.frame_order_header)
        self.lblCustomerBadge.setMinimumSize(QtCore.QSize(0, 28))
        self.lblCustomerBadge.setObjectName("lblCustomerBadge")
        self.gridLayout_order_header.addWidget(self.lblCustomerBadge, 1, 0, 1, 3)
        self.verticalLayout_order.addWidget(self.frame_order_header)
        self.scrollCart = QtWidgets.QScrollArea(parent=self.frame_order)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.scrollCart.sizePolicy().hasHeightForWidth())
        self.scrollCart.setSizePolicy(sizePolicy)
        self.scrollCart.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollCart.setWidgetResizable(True)
        self.scrollCart.setObjectName("scrollCart")
        self.widget_cart = QtWidgets.QWidget()
        self.widget_cart.setGeometry(QtCore.QRect(0, 0, 420, 427))
        self.widget_cart.setObjectName("widget_cart")
        self.verticalLayout_cart = QtWidgets.QVBoxLayout(self.widget_cart)
        self.verticalLayout_cart.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_cart.setSpacing(0)
        self.verticalLayout_cart.setObjectName("verticalLayout_cart")
        self.lblCartEmpty = QtWidgets.QLabel(parent=self.widget_cart)
        self.lblCartEmpty.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblCartEmpty.setFont(font)
        self.lblCartEmpty.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCartEmpty.setObjectName("lblCartEmpty")
        self.verticalLayout_cart.addWidget(self.lblCartEmpty)
        self.scrollCart.setWidget(self.widget_cart)
        self.verticalLayout_order.addWidget(self.scrollCart)
        self.frame_summary = QtWidgets.QFrame(parent=self.frame_order)
        self.frame_summary.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_summary.setObjectName("frame_summary")
        self.gridLayout_summary = QtWidgets.QGridLayout(self.frame_summary)
        self.gridLayout_summary.setContentsMargins(20, 16, 20, 16)
        self.gridLayout_summary.setObjectName("gridLayout_summary")
        self.lblSubTotalCaption = QtWidgets.QLabel(parent=self.frame_summary)
        self.lblSubTotalCaption.setObjectName("lblSubTotalCaption")
        self.gridLayout_summary.addWidget(self.lblSubTotalCaption, 0, 0, 1, 1)
        self.lblSubTotal = QtWidgets.QLabel(parent=self.frame_summary)
        self.lblSubTotal.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblSubTotal.setObjectName("lblSubTotal")
        self.gridLayout_summary.addWidget(self.lblSubTotal, 0, 1, 1, 1)
        self.btnEditDiscount = QtWidgets.QPushButton(parent=self.frame_summary)
        self.btnEditDiscount.setMinimumSize(QtCore.QSize(0, 26))
        self.btnEditDiscount.setObjectName("btnEditDiscount")
        self.gridLayout_summary.addWidget(self.btnEditDiscount, 1, 0, 1, 1)
        self.lblDiscount = QtWidgets.QLabel(parent=self.frame_summary)
        self.lblDiscount.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblDiscount.setObjectName("lblDiscount")
        self.gridLayout_summary.addWidget(self.lblDiscount, 1, 1, 1, 1)
        self.lblTaxCaption = QtWidgets.QLabel(parent=self.frame_summary)
        self.lblTaxCaption.setObjectName("lblTaxCaption")
        self.gridLayout_summary.addWidget(self.lblTaxCaption, 2, 0, 1, 1)
        self.lblTax = QtWidgets.QLabel(parent=self.frame_summary)
        self.lblTax.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblTax.setObjectName("lblTax")
        self.gridLayout_summary.addWidget(self.lblTax, 2, 1, 1, 1)
        self.line_summary = QtWidgets.QFrame(parent=self.frame_summary)
        self.line_summary.setMinimumSize(QtCore.QSize(0, 1))
        self.line_summary.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_summary.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_summary.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_summary.setObjectName("line_summary")
        self.gridLayout_summary.addWidget(self.line_summary, 3, 0, 1, 2)
        self.lblGrandTotalCaption = QtWidgets.QLabel(parent=self.frame_summary)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.lblGrandTotalCaption.setFont(font)
        self.lblGrandTotalCaption.setObjectName("lblGrandTotalCaption")
        self.gridLayout_summary.addWidget(self.lblGrandTotalCaption, 4, 0, 1, 1)
        self.lblGrandTotal = QtWidgets.QLabel(parent=self.frame_summary)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.lblGrandTotal.setFont(font)
        self.lblGrandTotal.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblGrandTotal.setObjectName("lblGrandTotal")
        self.gridLayout_summary.addWidget(self.lblGrandTotal, 4, 1, 1, 1)
        self.frame_payment_methods = QtWidgets.QFrame(parent=self.frame_summary)
        self.frame_payment_methods.setMinimumSize(QtCore.QSize(0, 66))
        self.frame_payment_methods.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_payment_methods.setObjectName("frame_payment_methods")
        self.horizontalLayout_payment_methods = QtWidgets.QHBoxLayout(self.frame_payment_methods)
        self.horizontalLayout_payment_methods.setContentsMargins(0, 6, 0, 0)
        self.horizontalLayout_payment_methods.setSpacing(10)
        self.horizontalLayout_payment_methods.setObjectName("horizontalLayout_payment_methods")
        self.btnPayCash = QtWidgets.QPushButton(parent=self.frame_payment_methods)
        self.btnPayCash.setMinimumSize(QtCore.QSize(0, 58))
        self.btnPayCash.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPayCash.setCheckable(True)
        self.btnPayCash.setChecked(True)
        self.btnPayCash.setObjectName("btnPayCash")
        self.horizontalLayout_payment_methods.addWidget(self.btnPayCash)
        self.btnPayCard = QtWidgets.QPushButton(parent=self.frame_payment_methods)
        self.btnPayCard.setMinimumSize(QtCore.QSize(0, 58))
        self.btnPayCard.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPayCard.setCheckable(True)
        self.btnPayCard.setObjectName("btnPayCard")
        self.horizontalLayout_payment_methods.addWidget(self.btnPayCard)
        self.btnPayTransfer = QtWidgets.QPushButton(parent=self.frame_payment_methods)
        self.btnPayTransfer.setMinimumSize(QtCore.QSize(0, 58))
        self.btnPayTransfer.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPayTransfer.setCheckable(True)
        self.btnPayTransfer.setObjectName("btnPayTransfer")
        self.horizontalLayout_payment_methods.addWidget(self.btnPayTransfer)
        self.gridLayout_summary.addWidget(self.frame_payment_methods, 5, 0, 1, 2)
        self.verticalLayout_order.addWidget(self.frame_summary)
        self.frame_checkout = QtWidgets.QFrame(parent=self.frame_order)
        self.frame_checkout.setMinimumSize(QtCore.QSize(0, 86))
        self.frame_checkout.setMaximumSize(QtCore.QSize(16777215, 86))
        self.frame_checkout.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_checkout.setObjectName("frame_checkout")
        self.verticalLayout_checkout = QtWidgets.QVBoxLayout(self.frame_checkout)
        self.verticalLayout_checkout.setContentsMargins(20, 14, 20, 18)
        self.verticalLayout_checkout.setObjectName("verticalLayout_checkout")
        self.btnCheckout = QtWidgets.QPushButton(parent=self.frame_checkout)
        self.btnCheckout.setMinimumSize(QtCore.QSize(0, 54))
        self.btnCheckout.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCheckout.setObjectName("btnCheckout")
        self.verticalLayout_checkout.addWidget(self.btnCheckout)
        self.verticalLayout_order.addWidget(self.frame_checkout)
        self.horizontalLayout.addWidget(self.frame_order)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblScanCaption.setText(_translate("Form", "Bán hàng"))
        self.lblCashierName.setText(_translate("Form", "Thu ngân: ---"))
        self.txtSearch.setPlaceholderText(_translate("Form", "Tìm sản phẩm theo tên hoặc mã vạch..."))
        self.btnFilter.setText(_translate("Form", "Lọc"))
        self.lblHintHelp.setText(_translate("Form", "<span style=\"background-color:#fbfcfd; border:1px solid #e2e8f0; padding:2px 6px; font-weight:bold; color:#0f172a;\">F1</span>&nbsp;<span style=\"color:#64748b;\">Trợ giúp</span>"))
        self.lblHintDiscount.setText(_translate("Form", "<span style=\"background-color:#fbfcfd; border:1px solid #e2e8f0; padding:2px 6px; font-weight:bold; color:#0f172a;\">F3</span>&nbsp;<span style=\"color:#64748b;\">Giảm giá</span>"))
        self.lblHintQuantity.setText(_translate("Form", "<span style=\"background-color:#fbfcfd; border:1px solid #e2e8f0; padding:2px 6px; font-weight:bold; color:#0f172a;\">F4</span>&nbsp;<span style=\"color:#64748b;\">Số lượng</span>"))
        self.lblHintPay.setText(_translate("Form", "<span style=\"background-color:#fbfcfd; border:1px solid #e2e8f0; padding:2px 6px; font-weight:bold; color:#0f172a;\">F9</span>&nbsp;<span style=\"color:#64748b;\">Thanh toán</span>"))
        self.lblOrderCode.setText(_translate("Form", "Đơn hàng mới"))
        self.btnAddCustomer.setToolTip(_translate("Form", "Gắn khách hàng vào hóa đơn"))
        self.btnAddCustomer.setText(_translate("Form", "+ Khách hàng"))
        self.btnClearCart.setToolTip(_translate("Form", "Xóa toàn bộ giỏ hàng"))
        self.lblCustomerBadge.setText(_translate("Form", "Khách hàng lẻ (Mặc định)"))
        self.lblCartEmpty.setText(_translate("Form", "Giỏ hàng đang trống"))
        self.lblSubTotalCaption.setText(_translate("Form", "Tạm tính (0 sản phẩm)"))
        self.lblSubTotal.setText(_translate("Form", "0 đ"))
        self.btnEditDiscount.setToolTip(_translate("Form", "Nhập mức giá cho hóa đơn"))
        self.btnEditDiscount.setText(_translate("Form", "Giảm giá"))
        self.lblDiscount.setText(_translate("Form", "0 đ"))
        self.lblTaxCaption.setText(_translate("Form", "Thuế VAT"))
        self.lblTax.setText(_translate("Form", "0 đ"))
        self.lblGrandTotalCaption.setText(_translate("Form", "Tổng thanh toán"))
        self.lblGrandTotal.setText(_translate("Form", "0 đ"))
        self.btnPayCash.setText(_translate("Form", "Tiền mặt"))
        self.btnPayCard.setText(_translate("Form", "Thẻ"))
        self.btnPayTransfer.setText(_translate("Form", "Chuyển khoản"))
        self.btnCheckout.setText(_translate("Form", "Hoàn tất đơn hàng"))
